#!/bin/sh
# preinst script for api

SMARTY_TEMPLATE_DIR=/var/www/capillary/api/templates_c
if [ ! -d "$SMARTY_TEMPLATE_DIR" ]; then
	mkdir "$SMARTY_TEMPLATE_DIR"
fi
chown www-data "$SMARTY_TEMPLATE_DIR"
chgrp www-data "$SMARTY_TEMPLATE_DIR"
exit 0
