<?php

define('ERR_RETURNED_ITEM_QTY_INVALID', 'ERR_RETURNED_ITEM_QTY_INVALID');
//macros for points engine errors
define("ERR_EM_UNAVAILABLE","ERR_EM_UNAVAILABLE");
define("ERR_EM_NOT_READY","ERR_EM_NOT_READY");
define("ERR_EM_NO_CONSUMERS_FOUND","ERR_EM_NO_CONSUMERS_FOUND");
define("ERR_PE_GENERIC","ERR_PE_GENERIC");
define("ERR_PE_OVER_LOADED","ERR_PE_OVER_LOADED");
define("ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION","ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION");
define("ERR_PE_TIMEOUT","ERR_PE_TIMEOUT");
define("ERR_PE_STOPPING","ERR_PE_STOPPING");
define("ERR_PE_PAM_NOT_READY","ERR_PE_PAM_NOT_READY");
define("ERR_PE_PAM_NOT_FOUND","ERR_PE_PAM_NOT_FOUND");
define("ERR_PE_EM_INVALID_EVAL_ID","ERR_PE_EM_INVALID_EVAL_ID");
define("ERR_PE_EM_EVAL_ID_NOT_FOUND","ERR_PE_EM_EVAL_ID_NOT_FOUND");
define("ERR_PE_INVALID_DATA","ERR_PE_INVALID_DATA");
define("ERR_PE_INVALID_PROGRAM_CONFIGURATION","ERR_PE_INVALID_PROGRAM_CONFIGURATION");

define('ERR_POINTS_RED_CANNOT_REDEEM_MORE_THAN_CURRENT_POINTS',-32000);
define('ERR_POINTS_RED_CANNOT_REDEEM_LESS_THAN_MIN_POINTS',-34000);
define('ERR_POINTS_RED_CANNOT_REDEEM_MORE_THAN_MAX_POINTS',-33000);
define('ERR_POINTS_RED_INSUFFICIENT_CURRENT_POINTS',-15000);
define('ERR_POINTS_RED_INSUFFICIENT_CUMULATIVE_POINTS',-16000);
define('ERR_POINTS_RED_INSUFFICIENT_CUMULATIVE_PURCHASES',-17000);
define('ERR_POINTS_RED_POINTS_NOT_DISIVIBILE',-18000);
define('ERR_LOYALTY_MISSED_CALL_NOT_RECIEVED', -19003);
define('ERR_LOYALTY_MISSED_CALL_REDEMPTION_DISABLED', -19004);
define('ERR_LOYALTY_SKIP_VALIDATION_NOT_ALLOWED', -19005);
define('ERR_LOYALTY_CLIENT_SIGNATURE_MISSING', -19006);

class ErrorCodes{

	static $api = array(
					'SUCCESS' => 200,
					'PARTIAL_SUCCESS'=>201,
					'FAIL'=>500,
					'INVALID_INPUT' => 400,
					'AUTHENTICATION_FAILURE' => 401,
					'UNSUPPORTED_VERSION' => 402,
					'UNSUPPORTED_RESOURCE' => 404,
					'UNSUPPORTED_HTTP_METHOD' => 405,
					'UNSUPPORTED_OPERATION' => 406,
					'SYSTEM_ERROR' => 407,
					'AUTH_FAIL_MAC_ID_MISMATCH' => 408
	);

	static $customer = array(
					'ERR_LOYALTY_SUCCESS' => 1000,
					'ERR_GET_SUCCESS' => 1000 ,
					'ERR_POST_SUBSCRIPTION_SUCCESS' => 1000,
					'ERR_GET_SUBSCRIPTION_SUCCESS' => 1000,
					'ERR_UPDATE_SUCCESS' => 1000,
					'ERR_COUPONS_SUCCESS' => 1000,
					'ERR_LOYALTY_INVALID_MOBILE'=> 1001,
					'ERR_LOYALTY_INVALID_EMAIL'=> 1002,
					'ERR_LOYALTY_INVALID_EXTERNAL_ID'=> 1003,
					'ERR_POPULATE_STORE'=>1004,
					'ERR_REGISTER_MOBILE_FAILED' =>1005,
					'ERR_MOBILE_REQUIRED' =>1006,
					'ERR_NO_MOBILE_EXT_EMAIL_ID' =>1007,
					'ERR_REGISTER_EXTERNAL_ID_FAILED' =>1008,
					'ERR_MLM_FAILED' => 1009,
					'ERR_UPDATE_POINTS_FAILED' => 1010,
					'ERR_NOT_REGISTERED' => 1011,
					'ERR_USER_NOT_REGISTERED' => 1012 ,
					'ERR_LOYALTY_NOT_REGISTERED' => 1013,
					'ERR_USER_ALREADY_REGISTERED' => 1014,
					'ERR_NO_IDENTIFIER' => 1015,
					'ERR_DUPLICATE_EMAIL' => 1016,
					'INVALID_CUSTOM_FIELD' => 1017 ,
					'ERR_CUSTOM_FIELD' => 1018,
					'ERR_ONLY_EMAIL_NOT_ALLOWED' => 1019,
					'-21000'  => 1003, //define(ERR_LOYALTY_INVALID_EXTERNAL_ID,
					'-19000'  => 1001, //define(ERR_LOYALTY_INVALID_MOBILE,
					'-27000'  => 1002, //define(ERR_LOYALTY_INVALID_EMAIL,
					'-1000' => 1020,   //define(ERR_LOYALTY_USER_NOT_REGISTERED,
					'-12000' => 1021,  //define(ERR_LOYALTY_INVALID_VALIDATION_CODE,
					'-7000' => 1023,   //define(ERR_LOYALTY_REGISTRATION_FAILED,
					'-6000' => 1024,   //define(ERR_LOYALTY_PROFILE_UPDATE_FAILED,
					'ERR_MANDATORY_FIELD_MISSING' => 1025,
					'ERR_OPTIONAL_FIELD_COUNT_MISMATCH' => 1026,
					'ERR_INVALID_VERIFICATION_FIELD' => 1027,
					'ERR_CUSTOMER_NOTES_SUCCESS_ADDED' => 1000,
					'ERR_CUSTOMER_NOTES_SUCCESS_RETRIEVED' => 1000,
					'ERR_CUSTOMER_NO_NOTES_AVAILABLE' => 1028,
					'ERR_CUSTOMER_PREFERENCES_SUCCESS_RETRIEVED' => 1000,
		             'ERR_CUSTOMER_TRACKERS_SUCCESS_RETRIEVED' =>1000,
					'ERR_CUSTOMER_PREFERENCES_RETRIEVED_FAILED' => 1029,
					'ERR_CUSTOMER_PREFERENCES_UPDATION_FAILED' => 1030,
					'ERR_CUSTOMER_PREFERENCES_UPDATION_SUCCESS' => 1000,
					'ERR_CUSTOMER_PREFERENCES_NOT_FOUND' => 1031,
					'ERR_DUPLICATE_MOBILE' => 1032,
					'ERR_DUPLICATE_EXTERNAL_ID' => 1033,
					'ERR_NO_REGISTRATION_DATE_NOT_IN_BOUNDRY' => 1034,
					'ERR_CUSTOMER_SOME_PREFERENCES_UPDATE_FAILED' => 1035,
					'ERR_CUSTOMER_SOME_NOTES_ADD_FAILED' => 1036,
					'ERR_CUSTOMER_NOTES_ADD_FAILED' => 1037,
					'ERR_REGISTER_EXTERNAL_ID_FAILED' => 1038,
					'ERR_EMAIL_REQUIRED' => 1039,
					'ERR_CUSTOMER_IDENTITY_CHANGE_REQUEST_SUCCESS' => 1040,
					'ERR_CUSTOMER_IDENTITY_CHANGE_REQUEST_FAILURE' => 1041,
					'ERR_NO_MOBILE-EXT-EMAIL_ID' => 1042,
					'ERR_EXTERNAL_ID_REQUIRED' => 1043,
       					'ERR_USER_PERMISSION_DENIED' => 1044,
		//Non loyalty  errors
					'ERR_NO_MOBILE_EMAIL_NON_LOYALTY' =>1045,
					'ERR_LOYALTY_TO_NON_LOYALTY_NOT_ALLOWED' =>1046,
					'ERR_MOBILE_REQUIRED_LOYALTY_CONVERSION' =>1047,
					'ERR_EMAIL_REQUIRED_LOYALTY_CONVERSION' =>1048,
					'ERR_EXTERNAL_ID_REQUIRED_LOYALTY_CONVERSION' =>1049,
					'ERR_MOBILE_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>1050,
					'ERR_EMAIL_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>1051,
					'ERR_EXTERNAL_ID_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>1052,

					"ERR_EM_UNAVAILABLE" =>1086,
					"ERR_EM_NOT_READY" =>1087,
					"ERR_EM_NO_CONSUMERS_FOUND" =>1088,
					"ERR_PE_GENERIC" => 1089,
					"ERR_PE_OVER_LOADED" =>1090,
					"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => 1091,
					"ERR_PE_TIMEOUT"=>1092,
					"ERR_PE_STOPPING"=>1093,
					"ERR_PE_PAM_NOT_READY"=>1094,
					"ERR_PE_PAM_NOT_FOUND" => 1095,
					"ERR_PE_EM_INVALID_EVAL_ID"=>1096,
					"ERR_PE_EM_EVAL_ID_NOT_FOUND" =>1097,
					"ERR_PE_INVALID_DATA"=>1098,
					"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=> 1099,

					'ERR_BATCH_LIMIT_EXCEEDED'=>1060,
					'ERR_INVALID_FRAUD_STATUS'=>1061,
					'ERR_INVALID_TEST_CONTROL_STATUS'=>1062,
				
					'ERR_INVALID_CHANNEL'=>1101,
					'ERR_INVALID_PRIORITY'=>1102,
					'ERR_INVALID_SCOPE'=>1103,
					'ERR_SUBSC_NO_IDENTIFIER'=>1104,
					'ERR_MULTIPLE_SCOPE'=>1105,
					'ERR_INVALID_SUBSCRIPTION_STATUS'=>1106,
                    'ERR_INVALID_CAMPAIGN_ID'=>1107,
                    'ERR_INVALID_OUTBOX_ID'=>1108,
					'ERR_FAILED_TO_GET_SUBSCRIPTION_DETAILS' => 1109,
					'ERR_FAILED_TO_SET_SUBSCRIPTION_DETAILS' => 1110,

					'ERR_RECOMMENDATION_FETCH_SUCCESS' => 1050,
					'ERR_RECOMMENDATION_FETCH_FAIL' => 1051,

					//referrals
					'ERR_REFERRAL_STATS_SUCCESS' => 1000,
					'ERR_REFERRAL_INVITE_SUCCESS' => 1000,
					'ERR_REFERRAL_SYS_ERROR' => 1222,
					'ERR_REFERRAL_INVALID_CAMPAIGN_TOKEN' => 1202,
					'ERR_REFERRAL_CAMPAIGN_NOT_IN_ORG' => 1203,
					'ERR_REFERRAL_REFER_FAILED' => 1204,
					'ERR_REFERRAL_INVALID_REFERRER' => 1205,
					'ERR_REFERRAL_INVALID_TYPE' => 1206,
					'ERR_REFERRAL_INVALID_INPUT' => 1207, 
			
					//tickets
					'ERR_TICKET_GET_SUCCESS'=>1300,
					'ERR_TICKET_ADD_SUCCESS'=>1300,
					'ERR_TICKET_CODE_EXISTS'=>1301,
					'ERR_TICKET_ADD_FAILED'=>1302,
					'ERR_TICKET_EMPTY_SUBJECT'=>1303,
			
	);


	static $transaction = array(
					"ERR_LOYALTY_INVALID_BILL_AMOUNT"=>601,
					"ERR_LOYALTY_INVALID_BILL_NUMBER" => 602,
					"ERR_LOYALTY_BILL_POINTS_USED" => 603,
					"ERR_LOYALTY_DUPLICATE_BILL_NUMBER" => 604,
					"ERR_INVALID_BILL_TYPE" => 605,
					"ERR_NO_IDENTIFIER" => 606,
					"ERR_NO_TRANSACTION_ID" => 607,
					"ERR_LOYALTY_BILL_ADDITION_FAILED" => 608,
					"ERR_LOYALTY_PROFILE_UPDATE_FAILED"=> 609,
					"ERR_LOYALTY_REGISTRATION_FAILED"=>610,
					"ERR_LOYALTY_USER_NOT_REGISTERED"=>611,
					"ERR_LOYALTY_BILL_CANCELLED" => 614,
					"ERR_NO_RECORDS"=>615,
					"ERR_INV_ITEM_DUPLICATE" =>	616,
					"ERR_INV_INVALID_ATTRIBUTE" => 617,
					"ERR_LOYALTY_FRAUD_USER" => 618,
					"NO_TRANSACTION_ID" => 619,
					"ERR_INVALID_ID" => 620,
					"ERR_LOYALTY_SUCCESS"=>600,
					"ERR_GET_SUCCESS" => 600,
					"ERR_NO_TRANSACTION_DATE_NOT_IN_BOUNDRY" => 621,
					"ERR_LINE_ITEM_ADDITION_FAILED" => 622,
					"ERR_TRIGGERING_SIDE_EFFECTS_FAILED" => 623,
					"ERR_LOYALTY_INVALID_RETURN_BILL_TIME" => 624,
					"ERR_LOYALTY_BILL_NUMBER_NOT_EXIST" => 625,
					"ERR_RETURNED_ITEM_QTY_INVALID" => 626,
					"ERR_LOYALTY_LINEITEM_QTY_NEGATIVE" => 627,
					"ERR_ALREADY_RETURNED_AND_OLD_TYPE_FULL" => 628,
					"ERR_ALREADY_RETURNED_AND_MORE_QTY" => 629,
					"ERR_ALREADY_RETURNED_AND_MORE_AMOUNT" => 630,
					"ERR_LOYALTY_BILL_AMOUNT_NEGATIVE" => 631,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_AMOUNT" => 632,
					"ERR_ALREADY_RETURNED_AND_OLD_TYPE_FULL" => 633,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_FULL" => 634,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_AMOUNT" => 635,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_LINEITEM" => 636,
				
					"-2000"   => 604, //define(ERR_LOYALTY_DUPLICATE_BILL_NUMBER,
					"-6000"   => 609, //define(ERR_LOYALTY_PROFILE_UPDATE_FAILED,
					"-7000"   => 610, //define(ERR_LOYALTY_REGISTRATION_FAILED,
					"-8000"   => 608, //define(ERR_LOYALTY_BILL_ADDITION_FAILED,
					"-11000"  => 602, //define(ERR_LOYALTY_INVALID_BILL_NUMBER,
					"-13000"  => 601, //define(ERR_LOYALTY_INVALID_BILL_AMOUNT,
					"-24000"  => 618, //define(ERR_LOYALTY_FRAUD_USER,
					"-25000"  => 603,  //define(ERR_LOYALTY_BILL_POINTS_USED,
					"ERR_RETURN_BILL_POINTS_COULD_NOT_BE_DEDUCTED" => 637,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_LINEITEM_OLD_AMOUNT" => 638,
					"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL" => 639,
					"ERR_NO_COUPON_POINTS" => 640,
					"ERR_USER_NOT_FOUND" => 641,
					"ERR_PREV_COUPONS_NON_REDEEMABLE" => 642,
					"ERR_NO_TRANSACTION_DATE_MORE_THAN_BOUNDRY" => 643,
					"ERR_NO_TRANSACTION_DATE_LESS_THAN_BOUNDRY" =>644,
					"ERR_NOT_INTERESTED_ADD_FAIL" => 645,
					"ERR_LOYALTY_INVALID_EMAIL" => 646,
					"ERR_DUPLICATE_EMAIL" => 647,
					"ERR_DUPLICATE_MOBILE" => 648,
					"ERR_LOYALTY_INVALID_MOBILE" => 649,
					"ERR_REGISTER_MOBILE_FAILED" => 650,
					"ERR_MOBILE_REQUIRED" => 651,
					"ERR_NO_MOBILE_EXT_EMAIL_ID" => 652,
					"ERR_DUPLICATE_EXTERNAL_ID" => 653,
					"ERR_REGISTER_EXTERNAL_ID_FAILED" => 654,
					"ERR_LOYALTY_NOT_REGISTERED" => 655,
					"ERR_USER_NOT_REGISTERED" => 656,
					"ERR_EUP_NOT_REGISTERED" => 657,
					"ERR_ONLY_EMAIL_NOT_ALLOWED" => 658,
					"ERR_EMAIL_REQUIRED" => 659,
					"ERR_NO_REGISTRATION_DATE_NOT_IN_BOUNDRY" => 660,
					"ERR_LOYALTY_LINEITEM_AMOUNT_NEGATIVE" => 661,
					"ERR_LOYALTY_LINEITEM_VALUE_NEGATIVE" => 662,
					"ERR_LOYALTY_LINEITEM_RATE_NEGATIVE" => 663,
					"ERR_LOYALTY_LINEITEM_DISCOUNT_NEGATIVE" => 664,
					"ERR_LOYALTY_BILL_GROSS_AMOUNT_NEGATIVE" => 665,
					"ERR_LOYALTY_BILL_DISCOUNT_NEGATIVE" => 666,
					"ERR_LOYALTY_TRANSACTION_NOT_FOUND_BY_ID" => 667,
					"ERR_LOYALTY_TRANSACTION_NOT_FOUND_BY_NUMBER" => 668,
					"ERR_CUSTOM_FIELD" => 669,
					"ERR_TRANSACTION_UPDATE_SUCCESS" => 600,
					'NO_TRANSACTION_ID_OR_NUMBER' => 670,

					'ERR_BATCH_LIMIT_EXCEEDED'=>672,
						
					"ERR_RETURN_TRANSACTION_NOT_SUPPORTED" => 673,
					"ERR_RETURN_LINEITEM_TRANSACTION_NOT_SUPPORTED" => 674,
					"ERR_RETURN_AMOUNT_TRANSACTION_NOT_SUPPORTED" => 675,
					"ERR_RETURN_FULL_TRANSACTION_NOT_SUPPORTED" => 676,
					"ERR_RETURN_TRANSACTION_NUMBER_EMPTY"	=> 677,
					"ERR_RETURNED_ITEM_AMOUNT_INVALID"		=> 678,
					"ERR_RETURN_LINEITEM_NOT_SPECIFIED" => 679,
			
					'ERR_TRANS_BLOCKED_CUSTOMER'	=> 681, 
			
					"ERR_EM_UNAVAILABLE" =>686,
					"ERR_EM_NOT_READY" =>687,
					"ERR_EM_NO_CONSUMERS_FOUND" =>688,
					"ERR_PE_GENERIC" => 689,
					"ERR_PE_OVER_LOADED" => 690,
					"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => 691,
					"ERR_PE_TIMEOUT"=>692,
					"ERR_PE_STOPPING"=>693,
					"ERR_PE_PAM_NOT_READY"=>694,
					"ERR_PE_PAM_NOT_FOUND" => 695,
					"ERR_PE_EM_INVALID_EVAL_ID"=>696,
					"ERR_PE_EM_EVAL_ID_NOT_FOUND" =>697,
					"ERR_PE_INVALID_DATA"=>698,
					"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=>699,
                    "ERR_INVALID_STORE_TILL_CODE"=>671,
                    "ERR_NO_TRANSACTION_RETRIEVED"=>680,
                    "ERR_INVALID_TRANSACTION_TYPE"=>1623,
                    "ERR_INSUFFICIENT_PARAMETERS"=>1624,
                    "ERR_NO_TARGET_TYPE"=>1625,
                    "ERR_UNSUPPORTED_TYPE_CHANGE" => 1626,
                    "ERR_ALREADY_RETRO" => 1627,
                    "ERR_NO_NI_TRANS" => 1628,
                    "ERR_CLIENT_SIGNATURE_MANDATORY" => 1629,
                    "ERR_RETRO_TRANSACTION_UPDATE_SUCCESS"=>1630,
					"ERR_RETRO_TRANSACTION_DISABLED"=>1631,
					'ERR_RETRO_OLD_TRANSACTION' => 1632,
					'ERR_RETRO_BEFORE_REGISTRATION' => 1633,
					'ERR_INVALID_RETURN_TYPE' =>1634,
                    'ERR_NO_RETURN_LI' =>1635,

                    'ERR_INVALID_TRANSACTION_STATUS' => 1636
	
			);


	static $coupon = array(
					 'ERR_COUPON_SUCCESS' => 700,
					 'ERR_USER_NOT_FOUND' => 701,
					 'ERR_INVALID_COUPON_CODE' => 702,
					 'ERR_INVALID_COUPON_USER' => 703,
					 'ERR_SMS_SENDING_ERROR' => 704,
					 'ERR_INVALID_INPUT' => 705,
					 'ERR_COUPON_REDEMPTION' => 706,
					 'ERR_INVALID_SERIES_ID' => 707,
					 'ERR_COUPON_FAIL' => 709,
					 'ERR_LOYALTY_FRAUD_USER' => 750,

					'VOUCHER_ERR_NOT_TRANSFERRABLE' => 710,
					'VOUCHER_ERR_ALREADY_USED' => 711,
					'VOUCHER_ERR_VCH_SERIES_VALID_DATE' => 712,
					'VOUCHER_ERR_VALID_CREATE_DAYS' => 713,
					'VOUCHER_ERR_REDEMPTIONS' => 714,
					'VOUCHER_ERR_INVALID_ORG' => 715,
					'VOUCHER_ERR_CANNOT_REDEEEM_MULTIPLE' => 716,
					'VOUCHER_ERR_BILL_NUMBER_NEEDED' => 718,
					'VOUCHER_ERR_INVALID_VOUCHER_CODE' => 719,
					'VOUCHER_ERR_TEST_VOUCHER_CODE' => 720,
					'VOUCHER_ERR_INVALID_USER' => 721,
					'VOUCHER_ERR_UNABLE_TO_CREATE' => 722,
					'VOUCHER_ERR_NOT_ISSUED_TO_CUSTOMER' => 723,
					'VOUCHER_ERR_COMMUNICATION' => 724,
					'VOUCHER_ERR_VALIDATION_REQUIRED' => 725,
					'VOUCHER_ERR_VALIDATION_NOT_REQUIRED' => 726,
					'VOUCHER_ERR_MAX_REDEMPTIONS_REACHED' => 728,
					'VOUCHER_ERR_VCH_INVALID_REDEMPTION_RANGE' => 729,
					'VOUCHER_ERR_UNKNOWN' => 730,
					'VOUCHER_ERR_SUCCESS' => 700,
					'VOUCHER_ERR_NO_MISSED_CALL' => 732,
					'VOUCHER_ERR_INVALID_BILL_AMOUNT' => 733,
					'VOUCHER_ERR_INVALID_STORE' => 735,
					'VOUCHER_ERR_ALLOWED_REDEMPTION_EXAUSTED' => 736,
					'VOUCHER_ERR_INVALID_REDEMPTION_GAP' => 738,
					'VOUCHER_ERR_INVALID_REDEMPTION_DATE' => 739,
					'VOUCHER_ERR_FRAUD_USER' => 740,
					'-3000'   => 702, //define(ERR_LOYALTY_INVALID_VOUCHER_CODE,
					'-10000'  => 707, //define(ERR_LOYALTY_REDEMPTION_SERIES_INVALID,
					'ERR_COUPON_SERIES_SUCCESS' => 700,
			
					'ERR_COUPON_BLOCKED_CUSTOMER' => 742,

					"ERR_EM_UNAVAILABLE" =>786,
					"ERR_EM_NOT_READY" =>787,
					"ERR_EM_NO_CONSUMERS_FOUND" =>788,
					"ERR_PE_GENERIC" => 789,
					"ERR_PE_OVER_LOADED" =>790,
					"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => 791,
					"ERR_PE_TIMEOUT"=>792,
					"ERR_PE_STOPPING"=>793,
					"ERR_PE_PAM_NOT_READY"=>794,
					"ERR_PE_PAM_NOT_FOUND" => 795,
					"ERR_PE_EM_INVALID_EVAL_ID"=>796,
					"ERR_PE_EM_EVAL_ID_NOT_FOUND" =>797,
					"ERR_PE_INVALID_DATA"=>798,
					"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=> 799
			);


	static $points = array(
		   'ERR_POINTS_SUCCESS' => 800,
	       'ERR_INVALID_POINTS' => 801,
		   'ERR_INVALID_IDENTIFIERS' => 802,
		   '-5000' => 818,  //define(ERR_LOYALTY_INSUFFICIENT_POINTS,
	 	   '-14000' => 803, //define(ERR_LOYALTY_INSUFFICIENT_REDEMPTION_POINTS,
 		   '-15000' => 804, //define(ERR_LOYALTY_INSUFFICIENT_CURRENT_POINTS,
           '-16000' => 805, //define(ERR_LOYALTY_INSUFFICIENT_LIFETIME_POINTS,
	       '-17000' => 806, //define(ERR_LOYALTY_INSUFFICIENT_LIFETIME_PURCHASE,
		   '-18000' => 807, //define(ERR_LOYALTY_REDEMPTION_POINTS_NOT_DIVISIBLE,
		   '-12000' => 808, //define(ERR_LOYALTY_INVALID_VALIDATION_CODE,
		   '-24000' => 809, //define(ERR_LOYALTY_FRAUD_USER,
		   '-20000'  => 819, //define(ERR_LOYALTY_COMMUNICATION,
		   '-4000'   => 850,
		   '-9000'   => 850,
		   '-26000'  => 850,
	       '-22000'  => 850,
	       '-23000'  => 850,
		   '-32000' => 818,
		   '-33000' => 819,
		   'ERR_LOYALTY_FRAUD_USER' => 820,
		   '-34000' => 821,
		   'ERR_POINTS_MISMATCH' => 810,
		   'ERR_POINTS_BILL_NOT_FOUND' => 811,
		   'ERR_POINTS_ALREADY_REVERTED_ON_BILL' => 812,
		   'ERR_NO_POINTS_REDEEMED_ON_BILL' => 814,
           'ERR_IN_POINTS_ENGINE' => 815,
		   'ERR_USER_NOT_FOUND' => 816,
		   'ERR_POINTS_FAIL' => 817,
		   'ERR_LOYALTY_CANNOT_REDEEM_MORE_THAN_CURRENT_POINTS' => 818,
		   'ERR_LOYALTY_CANNOT_REDEEM_MORE_THAN_MAX_POINTS' => 819,
           '-19003' => 822,
            '-19004' => 823,
            '-19005' => 824,
            '-19006' => 825,
			'-3309'	=> 826,		// invalid points catgeory
			'-3310'	=>  826,
			'-3311' => 813, 	// insufficients current points at warehouse.pa*
			"-520" => 827,
			"-410" => 828,
			"-411" => 829,
		   'ERR_POINTS_BLOCKED_CUSTOMER' => 821,
			"ERR_EM_UNAVAILABLE" =>886,
			"ERR_EM_NOT_READY" =>887,
			"ERR_EM_NO_CONSUMERS_FOUND" =>888,
			"ERR_PE_GENERIC" => 889,
			"ERR_PE_OVER_LOADED" =>890,
			"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => 891,
			"ERR_PE_TIMEOUT"=>892,
			"ERR_PE_STOPPING"=>893,
			"ERR_PE_PAM_NOT_READY"=>894,
			"ERR_PE_PAM_NOT_FOUND" => 895,
			"ERR_PE_EM_INVALID_EVAL_ID"=>896,
			"ERR_PE_EM_EVAL_ID_NOT_FOUND" =>897,
			"ERR_PE_INVALID_DATA"=>898,
			"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=> 899,
			"ERR_PE_INVALID_REDEMPTION_TIME"=>859,
                        "ERR_OTP_COMMUNICATION_FAILURE"=>860,
			'ERR_LOYALTY_NOT_REGISTERED'=>881,

	);

	static $product = array(
				'ERR_PRODUCT_SUCCESS' => 2100,
				'ERR_PRODUCT_FAILURE' => 2101,
				'ERR_PRODUCT_NO_ITEM_SKU' => 9102,
				'ERR_PRODUCT_NO_PRICE' => 9103,
				'ERR_PRODUCT_ADD_SUCCESS' => 9100,
				'ERR_PRODUCT_UPDATE_SUCCESS' => 9105,
				'ERR_PRODUCT_PRICE_NON_NUMERIC' => 9106,
				'ERR_PRODUCT_ADD_FAIL' => 9107,
				'ERR_DUPLICATE_ITEM_EAN' => 9108,
				'ERR_SIZE_ADD_FAIL' => 9109,
				'ERR_SIZE_ADD_SUCCESS' => 9110,
				'ERR_STYLE_SUCCESS' => 9120,
				'ERR_STYLE_FAILURE' => 9121,
				'ERR_SIZE_SUCCESS' => 9130,
				'ERR_SIZE_FAILURE' => 9131,
				'ERR_META_SIZE_SUCCESS' => 9140,
				'ERR_META_SIZE_FAILURE' => 9141,
				'ERR_ATTR_VALUE_SUCCESS' => 9150,
				'ERR_ATTR_VALUE_FAILURE' => 9151,
				'ERR_BRAND_SUCCESS' => 9160,
				'ERR_BRAND_FAILURE' => 9161,
				'ERR_BRAND_ADD_FAILURE' => 9170,
				'ERR_BRAND_ADD_SUCCESS' => 9171,
				'ERR_CATEGORY_SUCCESS' => 9172,
		 		'ERR_CATEGORY_FAILURE' => 9173,
		 		'ERR_CATEGORY_ADD_FAILURE' => 9174,
		 		'ERR_CATEGORY_ADD_SUCCESS' => 9175,
		 		'ERR_ATTR_SUCCESS' => 9176,
		 		'ERR_ATTR_FAILURE' => 9177,
				'ERR_COLOR_SUCCESS' => 9178,
		 		'ERR_COLOR_FAILURE' => 9179,
		 		'ERR_ATTRIBUTE_ADD_SUCCESS' => 9180,
		 		'ERR_ATTRIBUTE_ADD_FAILURE' => 9181,
		 		'ERR_NO_META_SIZE_CODE' => 9182,
		 		'ERR_NO_META_SIZE_FAMILY' => 9183,
		 		'ERR_NO_META_SIZE_TYPE' => 9184
			);

	static $organization = array(
				'ERR_ORG_SUCCESS' => 3200,
				'ERR_ORG_FAILURE' => 3201,
				'ERR_ENTITY_SEARCH_SUCCESS' => 3200,
				'ERR_ENTITY_SEARCH_FAIL' => 3202,
				'ERR_ORG_CUSTOM_FIELD_GET_SUCCESS' => 3200,
				'ERR_ORG_CUSTOM_FIELD_GET_FAIL' => 3203,
				'ERR_ORG_SCOPE_NOT_FOUND' => 3204,
				'ERR_ORG_CONFIG_ADD_SUCCESS' => 3205,
				'ERR_ORG_CONFIG_ADD_FAIL' => 3206,
				'ERR_CUSTOMER_TYPE_INVALID' => 3207,
				'ERR_ORG_CONFIG_FOUND' => 3208,
				'ERR_ORG_CONFIG_NOT_FOUND' => 3209,
				'ERR_ORG_CONFIG_INVALID_SCOPE' => 3211,
				'ERR_ORG_CONFIG_INVALID_VALUE' => 3212,
                                'ERR_ORG_SOURCE_MAPPING_INVALID_SHORTCODE' => 3213,
                                'ERR_ORG_SOURCE_MAPPING_INVALID_ACTION' => 3214,
                                'ERR_ORG_SOURCE_MAPPING_MISSING_MANDATORY_PARAMS' => 3215,
                                'ERR_ORG_SOURCE_MAPPING_DUPLICATE_MAPPING' => 3216,
                                'ERR_ORG_SOURCE_MAPPING_INVALID_TYPE' => 3217,
                                'ERR_ORG_SOURCE_MAPPING_ADD_SUCCESS' => 3218,
                                'ERR_ORG_SOURCE_MAPPING_INVALID_PARAM' => 3219,
                                'ERR_ORG_SOURCE_MAPPING_ADD_FAIL' => 3220,
                                'ERR_ORG_SOURCE_MAPPING_INVALID_COMMAND' => 3221,
                                'ERR_ORG_SOURCE_MAPPING_INCOMAPTIBLE_TYPE' => 3222,
                                'ERR_CURRENCY_SUCCESS' => 3223,
                                'ERR_CURRENCY_FAILURE' => 3224, 
                                'ERR_SOURCE_MAPPING_USE_ORG_PREFIX_NOT_SET' => 3225, 
                                'ERR_SOURCE_MAPPING_ORG_PREFIX_VALUE_NOT_SET' => 3226, 
                                'ERR_SOURCE_MAPPING_ORG_PREFIX_EXISTING_COMMAND' => 3227, 
				'ERR_SOURCE_MAPPING_ORG_PREFIX_NOT_FOUND' => 3228,
               'ERR_ORG_SOURCE_MAPPING_INVALID_TILL' => 3229
			);

	static $communications = array(
				'ERR_SMS_SEND_SUCCESS' => 4100,
				'ERR_EMAIL_SEND_SUCCESS' => 4200,
				'ERR_SMS_FETCH_SUCCESS' => 4100,
				'ERR_EMAIL_FETCH_SUCCESS' => 4200,
				'ERR_SMS_SEND_FAIL' => 4101,
				'ERR_EMAIL_SEND_FAIL' => 4201,
				'ERR_SMS_NOT_FOUND' => 4102,
				'ERR_EMAIL_NOT_FOUND' => 4202,
				'ERR_UPDATE_TEMPLATE_SUCCESS' => 4100,
				'ERR_ADD_TEMPLATE_SUCCESS' => 4100,
				'ERR_INVALID_TEMPLATE_TYPE' =>4203,
				'ERR_ADD_TEMPLATE_FAILED' => 4204,
				'ERR_UPDATE_TEMPLATE_FAILED' => 4205,
				'ERR_INVALID_TEMPLATE_ID' => 4206,
				'ERR_NO_TEMPLATE_FOUND' => 4207,
				'ERR_EMAIL_INVALID' => 4208
	);

	static $associate = array(
			'ERR_ASSOC_LOGIN_SUCCESS' => 200,
			'ERR_ASSOC_LOGIN_FAIL' => 401,
			'ERR_ASSOC_LOGIN_NO_IDENTIFIER' => 5002,
			'ERR_ASSOC_LOGIN_NO_ASSOC_CREDEINTIAL' => 5003,
			'ERR_ASSOC_UPDATE_SUCCESS' => 2100,
			'ERR_ASSOC_ACTIVITY_SUCCESS' => 2200,
			'ERR_ASSOC_GET_SUCCESS' => 2300,
			'ERR_ASSOC_GET_FAIL' => 2301
	);

	static $stores = array(
			'ERR_STORE_GET_SUCCESS' => 900,
			'ERR_STORE_GET_FAILURE' => 901,
			'ERR_INVALID_STORE_IDENTIFIER' => 902,
			'ERR_NO_STORE_ID' => 903,
            'ERR_CLIENTLOG_SIZE_MISMATCH' => 904,
            'ERR_CLIENTLOG_SIGN_MISMATCH' => 905,
            'ERR_CLIENTLOG_FILESERVICE_UPLOAD_FAIL' => 906,
            'ERR_CLIENTLOG_META_DBWRITE_FAIL' => 907,
			'ERR_TASK_GET_FAILURE' => 908,
			'ERR_NO_TASK_FOUND' => 909,
			'ERR_TASK_GET_SUCCESS' => 910,
			'ERR_STORE_INVALID_REPORT_TYPE' => 911,
			'ERR_STORE_REPORT_ADD_SUCCESS' => 900,
			'ERR_STORE_REPORT_ADD_FAIL' => 912,
			'ERR_STORE_REPORT_GET_SUCCESS' => 900,
			'ERR_NO_IDENTIFIER' => 913,
            'ERR_SS_DIAG_LOG_NOT_UPLOADABLE' => 905,
            'ERR_STORE_REP_PARTIAL_SUC' => 921,
            'ERR_STORE_REP_FULL_FAIL' => 922,
            'ERR_TILL_DIAG_PARTIAL_SUC' => 923,
            'ERR_TILL_DIAG_FULL_FAIL' => 924,
			'ERR_INVALID_DATA' => 925
	);

	static $tasks = array(
			'ERR_TASK_GET_SUCCESS' => 5200,
			'ERR_TASK_META_SUCCESS' => 5200,
			'ERR_TASK_ADD_SUCCESS' => 5200,
			'ERR_TASK_UPDATE_SUCCSS' => 5200,
			'ERR_TASK_FETCH_UPDATE_LOG_SUCCESS' => 5200,
			'ERR_TASK_STATUS_ADD_SUCCESS' => 5200,
			'ERR_TASK_GET_FAILURE' => 5201,
			'ERR_TASK_META_FAILURE' => 5201,
			'ERR_TASK_ADD_FAILURE' => 5201,
			'ERR_TASK_UPDATE_FAILURE' => 5201,
			'ERR_TASK_NO_IDENTIFIER_PASSED' => 5203,
			'ERR_TASK_ID_INVALID' => 5204,
			'ERR_TASK_INVALID_PARAMS' => 5205,
			'ERR_TASK_REMINDER_ADDITION_SUCCESS' => 5200,
			'ERR_TASK_REMINDER_ADDITION_FAIL' => 5206,
			'ERR_TASK_STATUS_ADDITION_SUCCESS' => 5200,
			'ERR_TASK_STATUS_ADDITION_FAIL' => 5206,
			'ERR_TASK_NO_VALID_STATUS' => 5207,
			'ERR_TASK_INVALID_INTERNAL_STATUS' => 5208,
			'ERR_TASK_END_DATE_NOT_IN_BOUNDARY' => 5208,
			'ERR_TASK_EXPIRY_DATE_NOT_IN_BOUNDARY' => 5209,
			'ERR_NO_TASK_FOUND' => 5211,
			'ERR_TASK_REMINDEE_ID_INVALID' => 5212,
			'ERR_TASK_CREATED_BY_ID_INVALID' => 5213,
			'ERR_TASK_CUSTOMER_NOT_REGISTERED' => 5212,
			'ERR_TASK_SOME_CUSTOMERS_NOT_REGISTERED' => 5213, 
			'ERR_TASK_SET_STORE_ID_WHEN_ADMIN_USER' => 5214
	);
	
	static $request = array(
			'ERR_REQUEST_GET_SUCCESS' => 9000,
			'ERR_CIR_ADD_SUCCESS'=>9000,
			'ERR_GW_ADD_SUCCESS'=>9000,
			'ERR_RETRO_TXN_ADD_SUCCESS' => 9000,
			'ERR_RETRO_TXN_APPROVE_SUCCESS' => 9000, 
			'ERR_RETRO_TXN_REJECT_SUCCESS' => 9000, 
			'ERR_REQUEST_UPDATE_SUCCESS'=>9000,
			'ERR_CIR_INVALID_EMAIL' => 9001,
			'ERR_CIR_DUPLICATE_EMAIL' => 9002,
			'ERR_CIR_DUPLICATE_EXTERNAL_ID' => 9003,
			'ERR_CIR_LOYALTY_INVALID_MOBILE' => 9004,
			'ERR_CIR_DUPLICATE_MOBILE' => 9005,
			'ERR_INVALID_REQUEST_TYPE' => 9006,
			'ERR_CIR_INVALID_TARGET_USER' => 9007,
			'ERR_INVALID_REQUEST_BASE_TYPE' => 9008,
			'ERR_REQUEST_ADD_FAILED' => 9009,
			'ERR_USER_NOT_REGISTERED' => 9011,
			'ERR_CIR_INVALID_OLD_VALUE' => 9012,
			'ERR_REQUEST_NOT_FOUND' => 9013,
			'ERR_REQUEST_APPROVE_FAILED' => 9014,
			'ERR_REQUEST_APPROVE_POINTS_FAILED' => 9015,
			'ERR_REQUEST_APPROVE_COUPON_FAILED' => 9016,
			'ERR_REQUEST_INVALID_SERIES' => 9017,
			'ERR_REQUEST_MERGE_EXISTS_VICTIM' => 9018,
			'ERR_NO_IDENTIFIER' => 9019,
			'ERR_REQUEST_DATE_FUTURE' => 9021,
			'ERR_LOYALTY_NOT_REGISTERED' => 9022,
			'ERR_REQUEST_SURVIVOR_MERGED' => 9023,
			'ERR_CIR_INVALID_NEW_VALUE' => 9024,
			'ERR_REQUEST_INVALID_POINTS' => 9025,
			'ERR_REQUEST_MERGE_EXISTS_SURVIVOR' => 9026,
			'ERR_REQUEST_VICTIM_MERGED' => 9027,
			'ERR_REQUEST_NEW_VALUE_DUPLICATE' => 9028,
			'ERR_CIR_VICTIM_SURVIVOR_SAME' => 9029,
			'ERR_CIR_OLD_NEW_VALUE_SAME' => 9031,
			'ERR_REQUEST_REJECT_REASON_EMPTY' => 9032,
			'ERR_REQUEST_REJECT_COMMENTS_EMPTY' => 9033,
			'ERR_REQUEST_REJECT_FAILED' => 9034,
			'ERR_REQUEST_REALLOC_EXISTS' => 9035,
			'ERR_REQUEST_INVALID_DATE' => 9036,
			'ERR_CIR_NON_LOYALTY_SURVIVOR' => 9037,
			'ERR_CIR_NON_LOYALTY_VICTIM' => 9038,
			'ERR_CIR_VICTIM_FRAUD' => 9039,
			'ERR_CIR_SURVIVOR_FRAUD' => 9041,
			'ERR_RETRO_INVALID_TRANSACTION' => 9051,
			'ERR_RETRO_OLD_TRANSACTION' => 9052,
			'ERR_RETRO_BEFORE_REGISTRATION' => 9053,
			'ERR_RETRO_INVALID_CUSTOMER' => 9054,
			'ERR_RETRO_DUPLICATE_REQUEST' => 9055,
			'ERR_REQUESTER_CANNOT_APPROVE' => 9056,
			'ERR_RETRO_INVALID_OLD_TXN_TYPE' => 9057,
			'ERR_RETRO_INVALID_NEW_TXN_TYPE' => 9058,
			'ERR_RETRO_AUTO_APPROVE_MAX_AMOUNT_EXCEED' => 9059,
			'ERR_RETRO_NOT_ENABLED' => 9060, 
			'ERR_RETRO_INVALID_BASE_TYPE' => 9061, 
			'ERR_GW_AUTO_APPROVAL_INVALID_INCENTIVE' => 9062
	);

	static $ftp_fetch_file = array(
			'ERR_FTP_CONNECTION_FAIL' =>  7201,
			'ERR_XML_TRANSFORMER_NOT_SUPPORTED' => 7202,
			'ERR_RESPONSE_HANDLER_NOT_SUPPORTED' => 7203,
			'ERR_STORE_FINDER_NOT_SUPPORTED' => 7204
	);

	static $auth_service = array(
			'ERR_LOGIN_SUCCESS' => 6200,
			'ERR_LOGIN_FAIL' => 6500,
			'ERR_CONQUEST_NOT_ENABLED' => 6501,
			'ERR_COOKIE_INVALID' => 6502,
			'ERR_PASSWORD_EXPIRED' => 6503
	);
	
	static $style = array(
			'ERR_STYLE_ADD_SUCCESS' => 6700,
			'ERR_STYLE_ADD_FAIL' => 6701,
			'ERR_STYLE_GET_SUCCESS' => 6702,
			'ERR_STYLE_GET_FAIL' => 6703
	);

	static function getCustomerErrorCode( $err_code )
	{
		return (string)self::$customer[ $err_code ];
	}

	static function getTransactionErrorCode( $err_code )
	{
		return (string)self::$transaction[ $err_code ];
	}

}


class ErrorMessage{

	static $api = array(
					'SUCCESS' => 'SUCCESS',
					'PARTIAL_SUCCESS' => 'Some requests have failed due to errors',
					'FAIL'=>'All requests have failed due to errors',
					'INVALID_INPUT' => 'Input is invalid, Please check request parameters or input xml/json',
					'AUTHENTICATION_FAILURE' => 'Please check your username/password or authentication token',
					'UNSUPPORTED_RESOURCE' => 'Incorrect resource',
					'UNSUPPORTED_VERSION' => 'Version is not supported for this resource',
					'UNSUPPORTED_OPERATION' => 'Operation is not supported for the resource',
					'UNSUPPORTED_HTTP_METHOD' => 'Incorrect HTTP Method',
					'SYSTEM_ERROR' => 'Unknown Error happened while processing the request',
					'AUTH_FAIL_MAC_ID_MISMATCH' => 'Network MAC ID does not match'
					);


					static $transaction = array(
				"ERR_GET_SUCCESS" => "Transaction retrieved successfully" ,
				"ERR_INVALID_ID" => "Invalid Transaction ID",
				"NO_TRANSACTION_ID" => "Transaction ID not provided" ,
				"ERR_INV_ITEM_DUPLICATE"	=>	"Duplicate item code in inventory",
				"ERR_INV_INVALID_ATTRIBUTE" =>  "Invalid attribute for the item",
				"ERR_LOYALTY_INVALID_BILL_AMOUNT"=>"Invalid transaction amount, quantity, rate or discount",
				"ERR_LOYALTY_FRAUD_USER" => "Not allowed - customer is marked as fraud.",
				"ERR_LOYALTY_INVALID_BILL_NUMBER" => "Invalid transaction number",
				"ERR_LOYALTY_BILL_POINTS_USED" => "Not allowed - points used for the transaction",
				"ERR_LOYALTY_DUPLICATE_BILL_NUMBER" => "Duplicate transaction number",
				"ERR_LOYALTY_BILL_ADDITION_FAILED" => "Transaction could not be added",
				"ERR_LINE_ITEM_ADDITION_FAILED" => "Line Item could not be added",
				"ERR_LOYALTY_PROFILE_UPDATE_FAILED"=>"update failed. Please check all the fields",
				"ERR_LOYALTY_REGISTRATION_FAILED"=>"Registration failed. Please check all the fields",
				"ERR_LOYALTY_USER_NOT_REGISTERED"=>"Customer not registered for loyalty program",
				"ERR_LOYALTY_INVALID_BILL_NUMBER"=>"Invalid transaction number",
				"ERR_LOYALTY_BILL_CANCELLED" => "Transaction cancelled already",
				"ERR_NO_RECORDS"=>"No transactions passed",
				"ERR_INVALID_BILL_TYPE" => "Invalid transaction type passed..Only type regular, return , not_interested and not_interested_return supported",
				"ERR_NO_IDENTIFIER" => "No identifier passed. One of mobile, email or external_id need to be passed",
				"ERR_LOYALTY_SUCCESS" => "Transaction added successfully",
				"ERR_NO_TRANSACTION_ID" => "No transaction id passed",
				"ERR_NO_TRANSACTION_DATE_NOT_IN_BOUNDRY" => "Transaction date too ahead in the future, or too behind in past",
				"ERR_TRIGGERING_SIDE_EFFECTS_FAILED" => "Error in triggering side effects",
				"ERR_LOYALTY_INVALID_RETURN_BILL_TIME" => "Invalid return transaction time, Return transaction should happen after add transaction",
				"ERR_LOYALTY_BILL_NUMBER_NOT_EXIST" => "Transaction Number does not exist",
				"ERR_RETURNED_ITEM_QTY_INVALID" => "Quantity of returned item is more than purchased item",
				"ERR_LOYALTY_LINEITEM_QTY_NEGATIVE" => "Quantity can't be negative",
				"ERR_ALREADY_RETURNED_AND_OLD_TYPE_FULL" => "Transaction is already returned fully, you can't return that transaction again",
				"ERR_ALREADY_RETURNED_AND_MORE_QTY" => "Transaction is already returned and returned quantity is more than purchased quantity",
				"ERR_ALREADY_RETURNED_AND_MORE_AMOUNT" => "Transaction is already returned and total returned amount is more than purchase amount",
				"ERR_LOYALTY_BILL_AMOUNT_NEGATIVE" => "Transaction amount can not be negative.",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_AMOUNT" => "Transaction is already returned with return type LINE_ITEM, you can't return transaction with return type AMOUNT.",
				"ERR_ALREADY_RETURNED_AND_OLD_TYPE_FULL" => "Transaction is already fully returned, you can't return this transaction again",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_FULL" => "Transaction is already fully returned, you can't return full transaction again",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_AMOUNT" => "Transaction is already returned with return type AMOUNT, you can't return full transaction again",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL_OLD_LINEITEM" => "Transaction is already returned with return type LINEITEM, you can't return full transaction again, try returning by lineitems",
				"ERR_RETURN_TRANSACTION_NOT_SUPPORTED" => "Returning of transactions is not allowed",
				"ERR_RETURN_LINEITEM_TRANSACTION_NOT_SUPPORTED" => "Returning of line item is not allowed",
				"ERR_RETURN_AMOUNT_TRANSACTION_NOT_SUPPORTED" => "Returning of transaction amount is not allowed",
				"ERR_RETURN_FULL_TRANSACTION_NOT_SUPPORTED" => "Returning of a full transaction is not allowed",
				"ERR_RETURN_TRANSACTION_NUMBER_EMPTY" => "Transaction number to be returned is not set",
				"ERR_RETURNED_ITEM_AMOUNT_INVALID"	=> "Amount of returned item is more than purchased item",
				"ERR_RETURN_LINEITEM_NOT_SPECIFIED" => "Line items to be returned not specified", 
								
				"-2000"   => "Duplicate transaction number",
				"-6000"   => "update failed. Please check all the fields",
				"-7000"   => "Registration failed. Please check all the fields",
				"-8000"   => "Transaction could not be added",
				"-11000"  => "Invalid transaction number",
				"-13000"  => "Invalid transaction amount, quantity, rate or discount",
				"-24000"  => "Not allowed - customer is marked as fraud.",
				"-25000"  => "Not allowed - points used for the transaction",
				"ERR_RETURN_BILL_POINTS_COULD_NOT_BE_DEDUCTED" => "Points could not be deducted, please try again later.",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_LINEITEM_OLD_AMOUNT" => "Transaction is already returned with return type AMOUNT, you can't return again with return type LINE_ITEM",
				"ERR_ALREADY_RETURNED_AND_NEW_TYPE_FULL" => "Transaction is already returned, you can't return full transaction again",
				"ERR_NO_COUPON_POINTS" => "Neither coupons or point redemption available for given transaction",
				'ERR_USER_NOT_FOUND' => 'Cannot find customer for provided mobile/external-id/e-mail.',
				'ERR_PREV_COUPONS_NON_REDEEMABLE' => 'In case of transactional redemptions, previous coupon redemption already failed',
				"ERR_NO_TRANSACTION_DATE_MORE_THAN_BOUNDRY" => "Transaction date too ahead in the future.",
				"ERR_NO_TRANSACTION_DATE_LESS_THAN_BOUNDRY" => "Transaction date too behind in past.",
				"ERR_NOT_INTERESTED_ADD_FAIL" => "Transaction addition failed for not interested",
				"ERR_LOYALTY_INVALID_EMAIL" => "Error in customer registration: Invalid Email",
				"ERR_DUPLICATE_EMAIL" => "Error in customer registration: Email Id is already assigned to another customer",
				"ERR_DUPLICATE_MOBILE" => "Error in customer registration: Mobile Number is already assigned to another Customer",
				"ERR_LOYALTY_INVALID_MOBILE" => "Error in customer registration: Mobile number is invalid.",
				"ERR_REGISTER_MOBILE_FAILED" => "Error in customer registration: registration with mobile failed",
				"ERR_MOBILE_REQUIRED" => "Error in customer registration: Mobile number is required for registration.",
				"ERR_NO_MOBILE_EXT_EMAIL_ID" => "Error in customer registration: No Valid Mobile Number or External ID or Email provided. Required for registration.",
				"ERR_DUPLICATE_EXTERNAL_ID" => "Error in customer registration while adding Transaction: external id is already assigned to another customer",
				"ERR_REGISTER_EXTERNAL_ID_FAILED" => "Error in customer registration: registration with external_id failed",
				"ERR_LOYALTY_NOT_REGISTERED" => "Error in customer registration: Customer is not registered in loyalty program",
				"ERR_USER_NOT_REGISTERED" => "Cannot find customer for provided mobile/external-id/e-mail.",
				"ERR_EUP_NOT_REGISTERED" => "Error in customer registration: registration in EUP failed.",
				"ERR_ONLY_EMAIL_NOT_ALLOWED" => "Error in customer registration: only email is not allowed for registration",
				"ERR_EMAIL_REQUIRED" => "Error in customer registration: Email required",
				"ERR_EXTERNAL_ID_REQUIRED" => "Error in customer registration: External id required",
				"ERR_NO_REGISTRATION_DATE_NOT_IN_BOUNDRY" => 'Error in customer registration: registration date too ahead in the future, or too behind in past',
				"ERR_LOYALTY_LINEITEM_AMOUNT_NEGATIVE" => "lineitem with negative amount is not allowed",
				"ERR_LOYALTY_LINEITEM_VALUE_NEGATIVE" => "lineitem with negative value is not allowed",
				"ERR_LOYALTY_LINEITEM_RATE_NEGATIVE" => "lineitem with negative rate is not allowed",
				"ERR_LOYALTY_LINEITEM_DISCOUNT_NEGATIVE" => "lineitem with negative discount is not allowed",
				"ERR_LOYALTY_BILL_GROSS_AMOUNT_NEGATIVE" => "Transaction gross amount can't be negative",
				"ERR_LOYALTY_BILL_DISCOUNT_NEGATIVE" => "Transaction discount can't be negative",
				"ERR_LOYALTY_TRANSACTION_NOT_FOUND_BY_ID" => "Transaction id not found for this customer",
				"ERR_LOYALTY_TRANSACTION_NOT_FOUND_BY_NUMBER" => "Transaction number not found for this customer",
				"ERR_CUSTOM_FIELD" => "Unable to update custom field",
				"ERR_TRANSACTION_UPDATE_SUCCESS" => "Transaction updated successfully",
				"NO_TRANSACTION_ID_OR_NUMBER" => "Transaction Id or Number is not provided",

				//batch limit restriction
				'ERR_BATCH_LIMIT_EXCEEDED' => 'Batch limit exceeded',
							
				'ERR_TRANS_BLOCKED_CUSTOMER' => 'Transaction blocked for customer',

				"ERR_EM_UNAVAILABLE" => "Points processing failed",
				"ERR_EM_NOT_READY" => "Points processing failed",
				"ERR_EM_NO_CONSUMERS_FOUND" => "Invalid configuration. Please report to capillary support.",
				"ERR_PE_GENERIC" => "Points processing failed",
				"ERR_PE_OVER_LOADED" => "Points processing failed",
				"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => "Points processing failed",
				"ERR_PE_TIMEOUT"=>"Points processing failed",
				"ERR_PE_STOPPING"=>"Points processing failed",
				"ERR_PE_PAM_NOT_READY"=>"Points processing failed",
				"ERR_PE_PAM_NOT_FOUND" => "Invalid configuration. Please report to capillary support.",
				"ERR_PE_EM_INVALID_EVAL_ID"=>"Points processing failed",
				"ERR_PE_EM_EVAL_ID_NOT_FOUND" => "Points processing failed",
				"ERR_PE_INVALID_DATA"=>"Points processing failed",
				"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=>"Invalid configuration. Please report to capillary support.",
                        "ERR_INVALID_STORE_TILL_CODE" => "Invalid store/till code passed",
                        "ERR_NO_TRANSACTION_RETRIEVED" => "No transaction retrieved",
                        "ERR_INVALID_TRANSACTION_TYPE"=>"Invalid transaction type passed",
                        "ERR_INSUFFICIENT_PARAMETERS"=>"Insufficient parameters passed to fetch transactions",
                        "ERR_NO_TARGET_TYPE"=>"No target type specified for update",
                        "ERR_UNSUPPORTED_TYPE_CHANGE" => "Requested transaction type change is not allowed",
                        "ERR_ALREADY_RETRO" => "Transaction already marked retro",
                        "ERR_NO_NI_TRANS" => "Invalid transaction ID",
                        "ERR_CLIENT_SIGNATURE_MANDATORY" => "Client signature is mandatory for this action",
                        "ERR_RETRO_TRANSACTION_UPDATE_SUCCESS" => "Transaction retrospectively marked REGULAR",
						"ERR_RETRO_TRANSACTION_DISABLED" => "Retro Transaction not available for this org",
						'ERR_RETRO_OLD_TRANSACTION' => "Transaction is too old to mark as retro",
						'ERR_RETRO_BEFORE_REGISTRATION' => "Registration is too much older than transaction time",
                        'ERR_INVALID_RETURN_TYPE'  =>"Requested return type is not allowed",
                        'ERR_NO_RETURN_LI'  => "No line items passed for lineitem return",
						
						'ERR_INVALID_TRANSACTION_STATUS' => 'Invalid transaction status provided'
				);

				static $customer = array(
				'ERR_LOYALTY_SUCCESS' => 'Customer registration successful',
				'INVALID_CUSTOM_FIELD' => 'Provided Custom Field is invalid' ,
				'ERR_POST_SUBSCRIPTION_SUCCESS' => 'Subscription successfully updated',
				'ERR_GET_SUBSCRIPTION_SUCCESS' => 'Subscription successfully retrieved',
				'ERR_COUPONS_SUCCESS' => 'Coupons retrieved successfully',
				'ERR_GET_SUCCESS' => 'Customer successfully retrieved'  ,
				'ERR_UPDATE_SUCCESS' => 'Customer successfully updated.',
				'ERR_LOYALTY_INVALID_MOBILE'=>'Customer not registered. Mobile number provided is invalid.',
				'ERR_LOYALTY_INVALID_EXTERNAL_ID'=>'Customer not registered. External ID provided is invalid.',
				'ERR_REGISTER_MOBILE_FAILED' =>'Failed to register using mobile number.',
				'ERR_MOBILE_REQUIRED' =>'Mobile number required.',
				'ERR_NO_MOBILE_EXT_EMAIL_ID' =>'No Valid Mobile Number or External ID or Email provided, Required for registration or update.',
				'ERR_REGISTER_EXTERNAL_ID_FAILED' =>'Failed to register customer using external ID.',
				'ERR_MLM_FAILED' => 'Failed to add registered customer to MLM',
				'ERR_UPDATE_POINTS_FAILED' => 'Failed to update registered customer points.',
				'ERR_NOT_REGISTERED' => 'Cannot find customer for provided identifier.' ,
				'ERR_USER_NOT_REGISTERED' => 'Cannot find customer for provided mobile/external-id/e-mail.' ,
				'ERR_LOYALTY_NOT_REGISTERED' => 'Customer not registered for Loyalty Program.' ,
				'ERR_NO_IDENTIFIER' => 'No identifier provided to get loyalty users.',
				'ERR_DUPLICATE_EMAIL' => 'Email provided already exists for some other user',
				'ERR_DUPLICATE_MOBILE' => 'Mobile number provided already exists for some other user',
				'ERR_DUPLICATE_EXTERNAL_ID' => 'External Id provided already exists for some other user',
				'ERR_ONLY_EMAIL_NOT_ALLOWED' => 'Only Email Id is not allowed for registration, pass Mobile or ExternalId with Email Id',
				'-1000' => 'Loyalty customer not registered.',
				'-12000' => 'Invalid validation code.',
				'-7000' => 'Loyalty registration failed.',
				'-6000' => 'Profile update failed.',
				'-19000'  => 'Customer not registered. Mobile number provided is invalid.',
				'-27000'  => 'Invalid Email',
				'-21000'  => 'Customer not registered. External ID provided is invalid.',
				'ERR_LOYALTY_INVALID_EMAIL'=>'Invalid Email',
				'ERR_POPULATE_STORE'=>'Failed to populate store',
				'ERR_NO_MOBILE-EXT-EMAIL_ID' => 'No valid identifier - Mobile/Email/External-Id',
				"ERR_EXTERNAL_ID_REQUIRED" => "Error in customer registration: External id required",
				'ERR_CUSTOM_FIELD' => 'Custom field update failed',
				'ERR_USER_ALREADY_REGISTERED' => 'Customer already registered',
				'ERR_MANDATORY_FIELD_MISSING' => "Mandatory fields not matching for customer identity update",
				'ERR_OPTIONAL_FIELD_COUNT_MISMATCH' => "Optional field count match less than required",
				'ERR_INVALID_VERIFICATION_FIELD' => 'Invalid field name for verification',
				'ERR_CUSTOMER_NOTES_SUCCESS_ADDED' => "Customer note added/updated successfully",
				'ERR_CUSTOMER_NOTES_SUCCESS_RETRIEVED' => "Customer note retrieved successfully",
					'ERR_CUSTOMER_TRACKERS_SUCCESS_RETRIEVED' =>"Customer trackers retrieved successfully",
				'ERR_CUSTOMER_NO_NOTES_AVAILABLE' => 'No customer notes available',
				'ERR_CUSTOMER_PREFERENCES_SUCCESS_RETRIEVED' => 'Customer preferences retrieved successfully.',
				'ERR_CUSTOMER_PREFERENCES_RETRIEVED_FAILED' => 'Customer preferences retrieval unsuccessful.',
				'ERR_CUSTOMER_PREFERENCES_UPDATION_FAILED' => 'Customer preferences update failed.',
				'ERR_CUSTOMER_PREFERENCES_UPDATION_SUCCESS' => 'Customer preferences successfully Updated.',
				'ERR_CUSTOMER_PREFERENCES_NOT_FOUND' => 'No preferences set for this customer',
				'ERR_CUSTOMER_SOME_PREFERENCES_UPDATE_FAILED' => 'Some preferences could not be updated for customer',
				'ERR_NO_REGISTRATION_DATE_NOT_IN_BOUNDRY' => 'Registration date too ahead in the future, or too behind in past',
				'ERR_CUSTOMER_NAME_EMPTY' => 'Customer firstname/lastname empty',
				'ERR_CUSTOMER_SOME_NOTES_ADD_FAILED' => 'Some notes could not be added/updated for customer',
				'ERR_CUSTOMER_NOTES_ADD_FAILED' => 'Customer Notes addition/update Failed',
				'ERR_REGISTER_EXTERNAL_ID_FAILED' =>'Failed to register using external id.',
					'ERR_NO_MOBILE_EMAIL_NON_LOYALTY' => 'No valid identifier - Mobile/Email passed for non loyalty',
					'ERR_MOBILE_REQUIRED_LOYALTY_CONVERSION' =>'Mobile is required for loyalty customer',
					'ERR_EMAIL_REQUIRED_LOYALTY_CONVERSION' =>'Email is required for loyalty customer',
					'ERR_EXTERNAL_ID_REQUIRED_LOYALTY_CONVERSION' =>'External-id is required for loyalty customer',
					'ERR_MOBILE_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>'Mobile is primary identifier and required for loyalty customer',
					'ERR_EMAIL_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>'Email is primary identifier and required for loyalty customer',
					'ERR_EXTERNAL_ID_PRIMARY_IDENTIFIER_LOYALTY_CONVERSION' =>'External-id is primary identifier and required for loyalty customer',
				'ERR_LOYALTY_TO_NON_LOYALTY_NOT_ALLOWED' => 'Conversion from loyalty to non loyalty is not allowed',
				'ERR_CUSTOMER_IDENTITY_CHANGE_REQUEST_SUCCESS' => 'Customer identity change request added successfully',
				'ERR_CUSTOMER_IDENTITY_CHANGE_REQUEST_FAILURE' => 'Failed to add customer identity change request',
				'ERR_EMAIL_REQUIRED' => 'Email required.',
				"ERR_EM_UNAVAILABLE" => "Points processing failed",
				"ERR_EM_NOT_READY" => "Points processing failed",
				"ERR_EM_NO_CONSUMERS_FOUND" => "Can not award points. Please report to capillary support.",
				"ERR_PE_GENERIC" => "Points processing failed",
				"ERR_PE_OVER_LOADED" => "Points processing failed",
				"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => "Points processing failed",
				"ERR_PE_TIMEOUT"=>"Points processing failed",
				"ERR_PE_STOPPING"=>"Points processing failed",
				"ERR_PE_PAM_NOT_READY"=>"Points processing failed",
				"ERR_PE_PAM_NOT_FOUND" => "Points processing failed",
				"ERR_PE_EM_INVALID_EVAL_ID"=>"Points processing failed",
				"ERR_PE_EM_EVAL_ID_NOT_FOUND" => "Points processing failed",
				"ERR_PE_INVALID_DATA"=>"Points processing failed",
				"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=>"Points processing failed",
				"ERR_USER_PERMISSION_DENIED" => "No permission to view the customer",


				'ERR_INVALID_CHANNEL'=>'Invalid channel passed',
				'ERR_INVALID_SCOPE'=>'Invalid scope passed',
				'ERR_INVALID_PRIORITY'=>'Invalid priority passed',
				'ERR_SUBSC_NO_IDENTIFIER'=>'Invalid identifier or no identifier passed',
				'ERR_MULTIPLE_SCOPE'=>'Multiple scopes are passed',
				'ERR_INVALID_SUBSCRIPTION_STATUS'=>'Invalid subscription status passed',
                'ERR_INVALID_CAMPAIGN_ID'=>'Invalid campaign id passed',
                'ERR_INVALID_OUTBOX_ID'=>'Invalid outbox id passed',
				'ERR_FAILED_TO_GET_SUBSCRIPTION_DETAILS' => 'Failed to get the subscription details',
				'ERR_FAILED_TO_SET_SUBSCRIPTION_DETAILS' => 'Failed to update the subscription details',

				'ERR_RECOMMENDATION_FETCH_SUCCESS' => 'Customer recommendations fetch successful',
				'ERR_RECOMMENDATION_FETCH_FAIL' => 'Customer recommendations fetch unsuccessful',

				//batch limit restriction
				'ERR_BATCH_LIMIT_EXCEEDED' => 'Batch limit exceeded',
						
				'ERR_INVALID_FRAUD_STATUS' => 'Invalid Fraud status',
				'ERR_INVALID_TEST_CONTROL_STATUS' => 'Invalid Test & Control Status',

				//referrals
				'ERR_REFERRAL_STATS_SUCCESS' => 'Referral statistics retrieved successfully',
				'ERR_REFERRAL_INVITE_SUCCESS' => 'Referrals are invited successfully',
				'ERR_REFERRAL_SYS_ERROR' => 'Internal error with the referral system',
					'ERR_REFERRAL_INVALID_CAMPAIGN_TOKEN' => 'Campaign token passed is invalid',
					'ERR_REFERRAL_CAMPAIGN_NOT_IN_ORG' => 'Configured campaign is not valid',
					'ERR_REFERRAL_REFER_FAILED' => 'Referral failed for the current customer',
					'ERR_REFERRAL_INVALID_REFERRER' => 'Referrer is not part of the campaign configured',
					'ERR_REFERRAL_INVALID_TYPE' => 'Referral type is not supported', 
					'ERR_REFERRAL_INVALID_INPUT' => 'POST data is invalid - customer is missing', 
					
				//tickets
					'ERR_TICKET_GET_SUCCESS'=>'Ticket retrieved successfully',
					'ERR_TICKET_ADD_SUCCESS'=>'Ticket added successfully',
					'ERR_TICKET_CODE_EXISTS'=>'Ticket already exists with same subject',
					'ERR_TICKET_ADD_FAILED'=>'Ticket add failed',
					'ERR_TICKET_EMPTY_SUBJECT'=>'Ticket subject is mandatory and should not be empty'
						
				);


				static $coupon = array(
				  'ERR_COUPON_SUCCESS' => 'Coupon processing successful',
				  'ERR_USER_NOT_FOUND' => 'The customer could not be found. Please check mobile, email, external id passed',
				  'ERR_INVALID_COUPON_CODE' => 'Coupon code is invalid',
				  'ERR_INVALID_COUPON_USER' => 'Coupon not issued to this customer',
				  'ERR_SMS_SENDING_ERROR' => 'Error in sending coupon through SMS',
				  'ERR_INVALID_INPUT' => 'Both coupon code and validation code are invalid',
				  'ERR_INVALID_SERIES_ID' => 'Coupon Series ID is invalid',
				  'ERR_COUPON_FAIL' => 'Coupon processing failed',
				  'ERR_LOYALTY_FRAUD_USER' => 'Not allowed - customer is marked as fraud.',
					'VOUCHER_ERR_SUCCESS' => 'Coupon processing successful',
					'VOUCHER_ERR_NOT_TRANSFERRABLE' => 'Coupon is not meant for this customer',
					'VOUCHER_ERR_ALREADY_USED' => 'Coupon is already used',
					'VOUCHER_ERR_VCH_SERIES_VALID_DATE' => 'Coupon Series / Campaign has expired',
					'VOUCHER_ERR_VALID_CREATE_DAYS' => 'Coupon has expired',
					'VOUCHER_ERR_REDEMPTIONS' => 'Campaign over, it was first come first serve',
					'VOUCHER_ERR_INVALID_ORG' => 'Invalid organization',
					'VOUCHER_ERR_CANNOT_REDEEEM_MULTIPLE' => 'Cannot redeem same Coupon multiple times',
					'VOUCHER_ERR_BILL_NUMBER_NEEDED' => 'Transaction number needed for redemption',
					'VOUCHER_ERR_INVALID_VOUCHER_CODE' => 'Coupon code does not exist',
					'VOUCHER_ERR_TEST_VOUCHER_CODE' => 'Coupon is a test Coupon. Cannot be redeemed',
					'VOUCHER_ERR_INVALID_USER' => 'Invalid customer',
					'VOUCHER_ERR_UNABLE_TO_CREATE' => 'Unable to create coupon',
					'VOUCHER_ERR_NOT_ISSUED_TO_CUSTOMER' => 'Coupon not issued to this customer',
					'VOUCHER_ERR_COMMUNICATION' => 'Unable to communicate information to customer',
					'VOUCHER_ERR_VALIDATION_REQUIRED' => 'Validation required',
					'VOUCHER_ERR_VALIDATION_NOT_REQUIRED' => 'Validation not required',
					'VOUCHER_ERR_MAX_REDEMPTIONS_REACHED' => 'Maximum number of redemptions reached',
					'VOUCHER_ERR_UNKNOWN' => 'Unknown error',
					'VOUCHER_ERR_VCH_INVALID_REDEMPTION_RANGE' => 'Invalid redemption range For coupon series',
        			'VOUCHER_ERR_NO_MISSED_CALL' => 'No Missed call received from the customer',
        			'VOUCHER_ERR_INVALID_BILL_AMOUNT' => 'Invalid transaction amount',
					'VOUCHER_ERR_INVALID_STORE' => '-1111, Invalid store',
					'VOUCHER_ERR_ALLOWED_REDEMPTION_EXAUSTED' => '-2222, Allowed redemption consumed',
					'VOUCHER_ERR_INVALID_REDEMPTION_GAP' => '-2223, Allowed redemption gap is invalid',
					'VOUCHER_ERR_INVALID_REDEMPTION_DATE' => '-2224, Allowed redemption date is invalid',
					'VOUCHER_ERR_FRAUD_USER' => '-101, Fraud customer',
					'-3000'   => 'Coupon code is invalid',
					'-10000'  => 'Coupon Series ID is invalid',
					'ERR_COUPON_SERIES_SUCCESS' => 'Coupon series fetched successfully',
					"ERR_EM_UNAVAILABLE" => "Coupon processing failed, Please try again later",
					"ERR_EM_NOT_READY" => "Coupon processing failed, Please try again later",
					"ERR_EM_NO_CONSUMERS_FOUND" => "Invalid configuration. Please report to capillary support.",
					"ERR_PE_GENERIC" => "Coupon processing failed, Please try again later",
					"ERR_PE_OVER_LOADED" => "Coupon processing failed, Please try again later",
					"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => "Coupon processing failed, Please try again later",
					"ERR_PE_TIMEOUT"=>"Coupon processing failed, Please try again later",
					"ERR_PE_STOPPING"=>"Coupon processing failed, Please try again later",
					"ERR_PE_PAM_NOT_READY"=>"Coupon processing failed, Please try again later",
					"ERR_PE_PAM_NOT_FOUND" => "Invalid configuration. Please report to capillary support.",
					"ERR_PE_EM_INVALID_EVAL_ID"=>"Coupon processing failed, Please try again later",
					"ERR_PE_EM_EVAL_ID_NOT_FOUND" => "Coupon processing failed, Please try again later",
					"ERR_PE_INVALID_DATA"=>"Coupon processing failed, Please try again later",
					"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=>"Invalid configuration. Please report to capillary support.",
						
						'ERR_COUPON_BLOCKED_CUSTOMER' => 'Coupon issue and redemption blocked for customer',
					
				  );


				 static $points = array(
				   'ERR_POINTS_SUCCESS'	=> 'Points redeemed successfully',
				   'ERR_POINTS_FAIL' => 'Points redemption failed',
				   'ERR_INVALID_POINTS' => 'Trying to redeem invalid points',
				   'ERR_INVALID_IDENTIFIERS' => 'Invalid mobile/email or external_id',
				   '-5000' => 'Insufficient loyalty points',
				   '-14000' => 'Insufficient redemption points',
 		  		   '-15000' => 'Insufficient current points',
                   '-16000' => 'Insufficient lifetime points',
                   '-17000' => 'Insufficient lifetime purchase',
                   '-18000' => 'Redemptions points not divisible',
				   '-24000' => 'Customer is marked as fraud',
		   		   '-12000' => 'Invalid validation code',
				   '-20000' => 'Unable to send information to customer',
				   '-22000'  => 'Points processing failed, Please try again later',
				   '-23000'  => 'Points processing failed, Please try again later',
			 	   '-4000'   => 'Points processing failed, Please try again later',
			 	   '-9000'   => 'Points processing failed, Please try again later',
			 	   '-26000'  => 'Points processing failed, Please try again later',
				   '-32000' => "Current points are less than points requested for redemption",
				   '-33000' => "Trying to redeem points more than maximum points that can be redeemed",
				   '-34000' => "Trying to redeem points less than minimum points that can be redeemed",
				   'ERR_LOYALTY_FRAUD_USER' => 'Not allowed - customer is marked as fraud.',
				   'ERR_POINTS_MISMATCH' => 'Mismatch in points for revert API call',
		           'ERR_POINTS_BILL_NOT_FOUND' => 'Transaction not found for points redemption/revert',
			       'ERR_POINTS_ALREADY_REVERTED_ON_BILL' => "Points have already been reverted on this transaction",
				   'ERR_NO_POINTS_REDEEMED_ON_BILL' => "No points were redeemed on this transaction",
				   'ERR_USER_NOT_FOUND' => "Customer not found for organization",
				   'ERR_VALIDATION_CODE_ISSUE_FAIL' => "Validation code issue failed",
				   'ERR_LOYALTY_CANNOT_REDEEM_MORE_THAN_CURRENT_POINTS' => 'Current points are less than points requested for redemption',
				   'ERR_LOYALTY_CANNOT_REDEEM_MORE_THAN_MAX_POINTS' => 'Trying to redeem points more than maximum points that can be redeemed',
				 	"ERR_EM_UNAVAILABLE" => "Points processing failed, Please try again later",
				 	"ERR_EM_NOT_READY" => "Points processing failed, Please try again later",
				 	"ERR_EM_NO_CONSUMERS_FOUND" => "Invalid configuration. Please report to capillary support.",
				 	"ERR_PE_GENERIC" => "Points processing failed, Please try again later",
				 	"ERR_PE_OVER_LOADED" => "Points processing failed, Please try again later",
				 	"ERR_PE_UNCOMITTED_CUSTOMER_TRANSACTION" => "Points processing failed, Please try again later",
				 	"ERR_PE_TIMEOUT"=>"Points processing failed, Please try again later",
				 	"ERR_PE_STOPPING"=>"Points processing failed, Please try again later",
				 	"ERR_PE_PAM_NOT_READY"=>"Points processing failed, Please try again later",
				 	"ERR_PE_PAM_NOT_FOUND" => "Loyalty program not found",
				 	"ERR_PE_EM_INVALID_EVAL_ID"=>"Points processing failed, Please try again later",
				 	"ERR_PE_EM_EVAL_ID_NOT_FOUND" => "Points processing failed, Please try again later",
				 	"ERR_PE_INVALID_DATA"=>"Points processing failed, Please try again later",
				 	"ERR_PE_INVALID_PROGRAM_CONFIGURATION"=>"Invalid configuration. Please report to capillary support.",
				 	"ERR_PE_INVALID_REDEMPTION_TIME"=>"Invalid redemption time passed.",
                                     "-19003"=>"No missed call recieved to authenticate redemption",
                                     "-19004"=>"Redemption via missed call is not allowed",
				 	"ERR_PE_INVALID_REDEMPTION_TIME"=>"Invalid redemption time passed.",
				 	'ERR_POINTS_BLOCKED_CUSTOMER' => 'Points redemption blocked for the customer',
                                        'ERR_OTP_COMMUNICATION_FAILURE' => 'Failed sending OTP by {{CHANNEL}}',
                                        '-19005' => 'Skipping validation code check is not allowed',
                                        '-19006' => 'Client signature is mandatory to skip validation code check',
				 	'ERR_LOYALTY_NOT_REGISTERED' => 'Customer not registered for loyalty program',
				 	'-3309'	=> 'Point redemption failed, Redemption is not configured',
				 	'-3310'	=> 'Point redemption failed, Redemption is not configured',
				 	'-3311'	=>'Insufficient current points',
					"-520" => 'Point redemption failed, try again later',
					"-410" => 'Point redemption failed, try again later',
					"-411" => 'Point redemption failed, try again later',
				 		
				 );

				 static $product = array(
				 		'ERR_PRODUCT_SUCCESS' => "Product retrieval successful",
				 		'ERR_PRODUCT_FAILURE' => "Product retrieval unsuccessful ",
				 		'ERR_PRODUCT_NO_ITEM_SKU' => 'Item sku not passed',
				 		'ERR_PRODUCT_ADD_SUCCESS' => 'Product added successfully',
				 		'ERR_PRODUCT_NO_PRICE' => 'Product Price not passed',
				 		'ERR_PRODUCT_UPDATE_SUCCESS' => 'Product updated successfully',
				 		'ERR_PRODUCT_PRICE_NON_NUMERIC' => 'Product price is not numeric',
				 		'ERR_PRODUCT_ADD_FAIL' => 'Product add failed.',
				 		'ERR_DUPLICATE_ITEM_EAN' => 'Trying to add product with an already existing ean',
				 		'ERR_SIZE_ADD_FAIL' => 'Adding size failed',
				 		'ERR_SIZE_ADD_SUCCESS' => 'Adding size successful',
				 		'ERR_STYLE_SUCCESS' => 'Style retrieval successful',
				 		'ERR_STYLE_FAILURE' => 'Style retrieval failed',
				 		'ERR_SIZE_SUCCESS' => 'Size retrieval successful',
				 		'ERR_SIZE_FAILURE' => 'Size retrieval failed',
				 		'ERR_META_SIZE_FAILURE' => 'Meta size retrieval failed',
				 		'ERR_META_SIZE_SUCCESS' => 'Meta size retrieval successful',
				 		'ERR_ATTR_VALUE_SUCCESS' => 'Attribute values retrieval successful',
				 		'ERR_ATTR_VALUE_FAILURE' => 'Attribute values retrieval failure',
				 		'ERR_BRAND_SUCCESS' => 'Brand retrieval successful',
				 		'ERR_BRAND_FAILURE' => 'Brand retrieval failure',
				 		'ERR_BRAND_ADD_FAILURE' => 'Brand addition failed',
				 		'ERR_BRAND_ADD_SUCCESS' => 'Brand addition successful',
				 		'ERR_CATEGORY_SUCCESS' => 'Category retrieval successful',
				 		'ERR_CATEGORY_FAILURE' => 'Category retrieval failure',
				 		'ERR_CATEGORY_ADD_FAILURE' => 'Category addition failed',
				 		'ERR_CATEGORY_ADD_SUCCESS' => 'Category addition successful',
				 		'ERR_ATTR_SUCCESS' => 'Attribute retrieval successful',
				 		'ERR_ATTR_FAILURE' => 'Attribute retrieval failure',
				 		'ERR_COLOR_SUCCESS' => 'Color retrieval successful',
		 				'ERR_COLOR_FAILURE' => 'Color retrieval failure',
		 				'ERR_ATTRIBUTE_ADD_SUCCESS' => 'Attribute addition successfull',
		 				'ERR_ATTRIBUTE_ADD_FAILURE' => 'Attribute addition failure',
		 				'ERR_NO_META_SIZE_CODE' => 'Meta size name not passed',
		 				'ERR_NO_META_SIZE_FAMILY' => 'Meta size family not passed',
		 				'ERR_NO_META_SIZE_TYPE' => 'Meta size type not passed'
				 
				 		
				 );

				 static $organization = array(
				 		'ERR_ORG_SUCCESS' => "Operation successful for organization",
				 		'ERR_ORG_FAILURE' => "Operation unsuccessful for organization",
				 		'ERR_ENTITY_SEARCH_SUCCESS' => "Entity search successful",
				 		'ERR_ENTITY_SEARCH_FAIL' => "Entity not found",
				 		'ERR_ORG_CUSTOM_FIELD_GET_SUCCESS' => 'Custom fields fetch successful',
				 		'ERR_ORG_CUSTOM_FIELD_GET_FAIL' => 'Custom fields fetch failed',
				 		'ERR_ORG_SCOPE_NOT_FOUND' => 'Custom fields not found for given scope',
				 		'ERR_ORG_CONFIG_ADD_SUCCESS' => 'Organization configuration addition successful',
				 		'ERR_ORG_CONFIG_ADD_FAIL' => 'Organization configuration addition failure',
				 		'ERR_CUSTOMER_TYPE_INVALID' => 'type is invalid',
				 		'ERR_ORG_CONFIG_FOUND' => 'Organization configuration fetch successful',
				 		'ERR_ORG_CONFIG_NOT_FOUND' => 'Organization configuration not found',
				 		'ERR_ORG_CONFIG_INVALID_SCOPE' => 'Organization configuration invalid scope',
				 		'ERR_ORG_CONFIG_INVALID_VALUE' => 'Organization configuration invalid value',
                                                'ERR_ORG_SOURCE_MAPPING_INVALID_ACTION' => 'Invalid action provided',
                                                'ERR_ORG_SOURCE_MAPPING_MISSING_MANDATORY_PARAMS' => 'Mandatory parameters not provided',
                                                'ERR_ORG_SOURCE_MAPPING_INVALID_PARAM' => 'Invalid parameter provided',
                                                'ERR_ORG_SOURCE_MAPPING_DUPLICATE_MAPPING' => 'Duplicate mapping provided',
                                                'ERR_ORG_SOURCE_MAPPING_INVALID_TYPE' => 'Invalid interaction type provided',
                                                'ERR_ORG_SOURCE_MAPPING_ADD_SUCCESS' => 'Successfully added mapping',
                                                'ERR_ORG_SOURCE_MAPPING_ADD_FAIL' => 'Failed to update mapping',
                                                'ERR_ORG_SOURCE_MAPPING_INVALID_COMMAND' => 'Invalid command provided',
                                                'ERR_ORG_SOURCE_MAPPING_INVALID_SHORTCODE' => 'Invalid shortcode provided',
                                                'ERR_ORG_SOURCE_MAPPING_INCOMAPTIBLE_TYPE' => 'The action is incomaptible with given interaction type',
                                                'ERR_CURRENCY_SUCCESS' => 'Currency retrieval success',
                                                'ERR_CURRENCY_FAILURE' => 'Currency retrieval failure', 
                        'ERR_SOURCE_MAPPING_USE_ORG_PREFIX_NOT_SET' => 'Org-prefix (brand keyword) not set', 
                        'ERR_SOURCE_MAPPING_ORG_PREFIX_VALUE_NOT_SET' => 'Org-prefix (brand keyword) value not provided', 
                        'ERR_SOURCE_MAPPING_ORG_PREFIX_EXISTING_COMMAND' => 'Org-prefix already in use by an sms-mapping command', 
				 		'ERR_SOURCE_MAPPING_ORG_PREFIX_NOT_FOUND' => 'Organization prefix not set',
                        'ERR_ORG_SOURCE_MAPPING_INVALID_TILL' => 'Invalid till id provided'
				 );

				 static $communications = array(
 						 	'ERR_SMS_SEND_SUCCESS' => "Message sent successfully",
 						 	'ERR_EMAIL_SEND_SUCCESS' => "Email sent successfully",
 							'ERR_SMS_FETCH_SUCCESS' => "Message fetched successfully",
 							'ERR_EMAIL_FETCH_SUCCESS' => "Email fetched successfully",
 							'ERR_SMS_SEND_FAIL' => "Message sending failure",
 					 		'ERR_EMAIL_SEND_FAIL' => "Email sending failure",
 							'ERR_PARTIAL_SMS_SEND_FAIL' => "Some of the message sending failed",
 							'ERR_SMS_NOT_FOUND' => "Message not found, or message is not sent",
 							'ERR_EMAIL_NOT_FOUND' => "Email not found, or email is not sent",
				 			'ERR_UPDATE_TEMPLATE_SUCCESS' => "Template update successful",
				 			'ERR_ADD_TEMPLATE_SUCCESS' => "Template added successfully",
				 			'ERR_INVALID_TEMPLATE_TYPE' => "Template type is invalid",
				 			'ERR_ADD_TEMPLATE_FAILED' => "Template can't be added",
				 			'ERR_UPDATE_TEMPLATE_FAILED' => "Template can't be updated",
				 			'ERR_INVALID_TEMPLATE_ID' => "Template id is invalid",
				 			'ERR_NO_TEMPLATE_FOUND' => 'There are no templates available for the given parameters for this organization',
				 			'ERR_EMAIL_INVALID' => 'Invalid Email ID'
				 );

				 static $associate = array(
				 		'ERR_ASSOC_LOGIN_SUCCESS' => "Login successful",
				 		'ERR_ASSOC_LOGIN_FAIL' => "Login failed, Username or Password is wrong",
				 		'ERR_ASSOC_LOGIN_NO_IDENTIFIER' => "No Identifier passed for login as associate",
				 		'ERR_ASSOC_LOGIN_NO_ASSOC_CREDEINTIAL' => "No credential passed for login as associate",
				 		'ERR_ASSOC_UPDATE_SUCCESS' => "update successful",
				 		'ERR_ASSOC_ACTIVITY_SUCCESS' => "Activities fetched successfully",
				 		'ERR_ASSOC_GET_SUCCESS' => "Associate successfully retrieved ",
				 		'ERR_ASSOC_GET_FAIL' => "Associate not found"
				 );

				 static $stores = array(
				 		'ERR_STORE_GET_SUCCESS' => 'Store info retrieval successful',
				 		'ERR_STORE_GET_FAILURE' => 'Store info retrieval unsuccessful',
				 		'ERR_INVALID_STORE_IDENTIFIER' => 'Invalid store identifier',
				 		'ERR_NO_STORE_ID' => 'No Store ID passed',
                        'ERR_CLIENTLOG_SIZE_MISMATCH' => 'Client log file size passed does not match size uploaded on server',
                        'ERR_CLIENTLOG_SIGN_MISMATCH' => 'Client log file signature passed does not match file signature on server',
                        'ERR_CLIENTLOG_FILESERVICE_UPLOAD_FAIL' => 'Failed to upload client log file to file service',
                        'ERR_CLIENTLOG_META_DBWRITE_FAIL' => 'Failed to insert client log file metadata in db',
				 		'ERR_TASK_GET_FAILURE' => "Tasks retrieval unsuccessful",
				 		'ERR_NO_TASK_FOUND' => "No tasks found",
				 		'ERR_TASK_GET_SUCCESS' => "Tasks retrieval successful",
				 		'ERR_STORE_INVALID_REPORT_TYPE' => 'Report type is invalid',
				 		'ERR_STORE_REPORT_ADD_SUCCESS' => 'Report added successfully',
				 		'ERR_STORE_REPORT_ADD_FAIL' => 'Report addition failed',
				 		'ERR_STORE_REPORT_GET_SUCCESS' => 'Store report retrieved successfully',
				 		'ERR_NO_IDENTIFIER' => 'Identifier is not passed',
                        'ERR_STORE_REP_PARTIAL_SUC' => 'Some of store server stats failed to insert',
                        'ERR_STORE_REP_FULL_FAIL' => 'All store server stats failed to insert',
                        'ERR_TILL_DIAG_PARTIAL_SUC' => 'Failed to insert some of till diagnostic details',
                        'ERR_TILL_DIAG_FULL_FAIL' => 'All till diagnostics details failed to insert',
                        'ERR_SS_DIAG_LOG_NOT_UPLOADABLE' => 'Store server diagnostics log upload not enabled for this store server',
				 		'ERR_INVALID_DATA' => 'Invalid data'
				 );

				 static $tasks = array(
				 		'ERR_TASK_GET_SUCCESS' => "Tasks retrieval successful",
				 		'ERR_TASK_META_SUCCESS' => "Tasks metadata retrieval successful",
				 		'ERR_TASK_ADD_SUCCESS' => "Task added successfully",
				 		'ERR_TASK_UPDATE_SUCCSS' => "Task updated successfully",
				 		'ERR_TASK_FETCH_UPDATE_LOG_SUCCESS' => "Update log retrieval success",
				 		'ERR_TASK_GET_FAILURE' => "Tasks retrieval unsuccessful",
				 		'ERR_TASK_META_FAILURE' => "Tasks metadata retrieval unsuccessful",
				 		'ERR_TASK_ADD_FAILURE' => "Task addition failed",
				 		'ERR_TASK_UPDATE_FAILURE' => "Task update failed",
				 		'ERR_TASK_NO_IDENTIFIER_PASSED' => "No identifier passed",
				 		'ERR_TASK_ID_INVALID' => 'Task identifier is empty or invalid',
				 		'ERR_TASK_INVALID_PARAMS' => 'Some of the parameters is invalid, please check Parameters',
				 		'ERR_TASK_REMINDER_ADDITION_SUCCESS' => 'Reminder addition successful',
				 		'ERR_TASK_REMINDER_ADDITION_FAIL' => 'Failed to add reminder',
				 		'ERR_TASK_STATUS_ADDITION_SUCCESS' => 'Status mapping addition successful',
				 		'ERR_TASK_STATUS_ADDITION_FAIL' => 'Failed to add Status mapping',
				 		'ERR_TASK_INVALID_INTERNAL_STATUS' => 'Invalid internal status passed',

				 		'ERR_TASK_NO_VALID_STATUS' => 'No valid status passed',
				 		'ERR_TASK_END_DATE_NOT_IN_BOUNDARY' => 'Task end date should be greater than start date',
				 		'ERR_TASK_EXPIRY_DATE_NOT_IN_BOUNDARY' => 'Task expiry date should be greater than end date',
				 		'ERR_NO_TASK_FOUND' => 'No tasks found',
				 		'ERR_TASK_REMINDEE_ID_INVALID' => 'Task remindee id is invalid',
				 		'ERR_TASK_CREATED_BY_ID_INVALID' => 'Task created by id invalid',
				 		'ERR_TASK_CUSTOMER_NOT_REGISTERED' => 'Customers not registered for this organization',
				 		'ERR_TASK_SOME_CUSTOMERS_NOT_REGISTERED' => 'Some of the customers are not registered', 
				 		'ERR_TASK_SET_STORE_ID_WHEN_ADMIN_USER' => 'When admin user updates the task, store ID must be  provided'
				 );
				 
				 static $request = array(
				 		'ERR_REQUEST_GET_SUCCESS' => 'Request retrieved successfully',
						'ERR_CIR_ADD_SUCCESS'=> 'Change Identifier request added successfully',
				 		'ERR_GW_ADD_SUCCESS'=> 'Goodwill request added successfully',
				 		'ERR_RETRO_TXN_ADD_SUCCESS' => 'Retro request added successfully',
				 		'ERR_RETRO_TXN_APPROVE_SUCCESS' => 'Retro request approved successfully',
				 		'ERR_RETRO_TXN_REJECT_SUCCESS' => 'Retro request rejected successfully',
				 		'ERR_REQUEST_UPDATE_SUCCESS' => 'Request updated successfully',
				 		'ERR_CIR_INVALID_EMAIL' => 'Requested new Email is invalid',
				 		'ERR_CIR_DUPLICATE_EMAIL' => 'Requested new Email already exists',
				 		'ERR_CIR_DUPLICATE_EXTERNAL_ID' => 'Requested new External ID already exists',
				 		'ERR_CIR_LOYALTY_INVALID_MOBILE' => 'Requested new mobile is invalid',
				 		'ERR_CIR_DUPLICATE_MOBILE' =>'Requested new mobile already exists',
				 		'ERR_INVALID_REQUEST_TYPE' => 'Request Type is invalid',
				 		'ERR_INVALID_REQUEST_BASE_TYPE' => 'Request Base Type is invalid',
				 		'ERR_CIR_INVALID_TARGET_USER' => 'Target customer is not Existing or Invalid',
				 		'ERR_REQUEST_ADD_FAILED' => 'Request add failed due to internal error. Please try again later',
				 		'ERR_USER_NOT_REGISTERED' => 'User is not registered',
				 		'ERR_CIR_INVALID_OLD_VALUE' => 'Old value is invalid',
				 		'ERR_REQUEST_NOT_FOUND' => 'Request not found',
						'ERR_REQUEST_APPROVE_FAILED' => 'Request approve failed',
						'ERR_REQUEST_APPROVE_POINTS_FAILED' => 'Failed to allocate goodwill points',
						'ERR_REQUEST_APPROVE_COUPON_FAILED' => 'Failed to issue coupon',
				 		'ERR_REQUEST_INVALID_SERIES' => 'Invalid coupon series',
				 		'ERR_REQUEST_MERGE_EXISTS_VICTIM' => 'Request for Merge already exists for the victim in pending or processing state',
				 		'ERR_REQUEST_MERGE_EXISTS_SURVIVOR' => 'Request for Merge already exists for the survivor in pending or processing state',
				 		'ERR_NO_IDENTIFIER' => 'No customer identifiers passed',
				 		'ERR_REQUEST_DATE_FUTURE' => 'Requested On date is in future',
						'ERR_LOYALTY_NOT_REGISTERED' => 'Customer is not registered for Loyalty Program',
				 		'ERR_REQUEST_SURVIVOR_MERGED' => 'Survivor is already merged to another user as victim',
				 		'ERR_CIR_INVALID_NEW_VALUE' => 'New value is invalid',
				 		'ERR_REQUEST_INVALID_POINTS' => 'Invalid points to allocate',
						'ERR_REQUEST_VICTIM_MERGED' => 'Victim is already merged to another user',
				 		'ERR_REQUEST_NEW_VALUE_DUPLICATE' => 'Request already exists for same new value',
				 		'ERR_CIR_VICTIM_SURVIVOR_SAME' => 'Survivor and victim are same',
				 		'ERR_CIR_OLD_NEW_VALUE_SAME' => 'Old value is same as new value',
				 		'ERR_REQUEST_REJECT_REASON_EMPTY' => 'Reason for request reject is mandatory',
				 		'ERR_REQUEST_REJECT_COMMENTS_EMPTY' => 'Comments on request reject are mandatory',
				 		'ERR_REQUEST_REJECT_FAILED' => 'Request reject failed',
				 		'ERR_REQUEST_REALLOC_EXISTS' => 'Identifier reallocation request already exists in pending state for the customer',
				 		'ERR_REQUEST_INVALID_DATE' => 'Invalid date specified in date range',
				 		'ERR_CIR_NON_LOYALTY_SURVIVOR' => 'Survivor is not enrolled in loyalty program',
				 		'ERR_CIR_NON_LOYALTY_VICTIM' => 'Victim is not enrolled in loyalty program',
				 		'ERR_CIR_VICTIM_FRAUD' => 'Victim account is blocked as fraud',
						'ERR_CIR_SURVIVOR_FRAUD' => 'Survivor account is blocked as fraud',
				 		
				 		'ERR_RETRO_INVALID_TRANSACTION' => "Invalid transaction ID specified",
						'ERR_RETRO_OLD_TRANSACTION' => "Transaction is too old to mark as retro",
						'ERR_RETRO_BEFORE_REGISTRATION' => "Registration is too much older than transaction time",
						'ERR_RETRO_INVALID_CUSTOMER' => "Invalid customer information passed",
						'ERR_RETRO_DUPLICATE_REQUEST' => "Request has been queued earlier",
				 		"ERR_REQUESTER_CANNOT_APPROVE" => "Same user cannot request and approve", 
				 		'ERR_RETRO_INVALID_OLD_TXN_TYPE' => 'Invalid transaction old_type specified', 
				 		'ERR_RETRO_INVALID_NEW_TXN_TYPE' => 'Invalid transaction new_type specified', 
				 		'ERR_RETRO_AUTO_APPROVE_MAX_AMOUNT_EXCEED' => 'Transaction amount beyond autoapproval limit',
				 		'ERR_RETRO_NOT_ENABLED' => "Retro transactions are not permitted as per org-configs",
				 		'ERR_RETRO_INVALID_BASE_TYPE' => 'Invalid base_type for request specified', 
				 		'ERR_GW_AUTO_APPROVAL_INVALID_INCENTIVE' => 'When auto approving, goodwill incentive must also be specified'
				 );
				 	
				 static $ftp_fetch_file = array(
				 		'ERR_FTP_CONNECTION_FAIL' =>  'Fail to connect FTP server',
				 		'ERR_XML_TRANSFORMER_NOT_SUPPORTED' => 'XML Transformer not supported for the organization',
				 		'ERR_RESPONSE_HANDLER_NOT_SUPPORTED' => 'Response handler not supported for the organization',
				 		'ERR_STORE_FINDER_NOT_SUPPORTED' => 'Store finder not supported for the organization'
				 );

				 static $auth_service = array(
				 		'ERR_LOGIN_SUCCESS' => 'LogIn Successful',
				 		'ERR_LOGIN_FAIL' => 'Username or Password is invalid',
				 		'ERR_CONQUEST_NOT_ENABLED' => 'Conquest is not enabled for this organization',
				 		'ERR_COOKIE_INVALID' => 'Invalid cookie',
				 		'ERR_PASSWORD_EXPIRED' => 'Password has expired'
				 );
				 
				 static $style = array(
				 		'ERR_STYLE_ADD_SUCCESS' => 'Style added successfully',
				 		'ERR_STYLE_ADD_FAIL' => 'Style could not be added',
				 		'ERR_STYLE_GET_SUCCESS' => 'Style fetched successfully',
				 		'ERR_STYLE_GET_FAIL' => 'Style could not be fetched'
				 );

				  static function getCustomerErrorMessage( $err_code )
				  {
				  	return (string)self::$customer[ $err_code ];

				  }

				  static function getTransactionErrorMessage( $err_code )
				  {
				  	return (string)self::$transaction[ $err_code ];

				  }


}

