<wsdl:description xmlns:wsdl="http://www.w3.org/ns/wsdl" xmlns:wsoap="http://www.w3.org/ns/wsdl/soap" xmlns:whttp="http://www.w3.org/ns/wsdl/http" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://new.webservice.namespace" targetNamespace="http://new.webservice.namespace">
	
	<wsdl:types>
		<xs:schema xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" elementFormDefault="qualified">
		
			<xs:element name="root" type="CouponIssueRequest"/>		
			<xs:element name="response" type="CouponIssueResponse"/>
			<xs:element name="Authorization" type="xs:string"/>
			
			<xs:simpleType name="Date">
		        <xs:restriction base="xs:string">
		            <xs:pattern value="(\d{4})-([0,1][0-9])-([0-3][0-9])"></xs:pattern>
		        </xs:restriction>
		    </xs:simpleType>
			
			<xs:complexType name="CouponIssueRequest">
				<xs:sequence>
					<xs:element name="coupon" type="RequestCoupon" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="CouponIssueResponse">
				<xs:sequence>
					<xs:element name="status" type="Status" minOccurs="0"/>
					<xs:element name="coupon" type="ResponseCoupon" minOccurs="0"/>
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="RequestCoupon">
				<xs:sequence>
					<xs:element name="series_id" type="xs:string" minOccurs="0" />
					<xs:element name="customer" type="RequestCustomer" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>
			
			<xs:complexType name="RequestCustomer">
				<xs:sequence>
					<xs:element name="mobile" type="xs:string" minOccurs="0" />
					<xs:element name="email" type="xs:string" minOccurs="0" />
					<xs:element name="external_id" type="xs:string" minOccurs="0" />
				</xs:sequence>
			</xs:complexType>
			
			<!-- it is not valid as of now -->
			<!-- 
			<xs:complexType name="ResponseCoupon">
				<xs:all>
					<xs:element name="code" type="xs:string" minOccurs="0" />
					<xs:element name="valid_till" type="Date" minOccurs="0" />
					<xs:element name="series_info" type="SeriesInfo" minOccurs="0" />
					<xs:element name="customer" type="ResponseCustomer" minOccurs="0" />
					<xs:element name="item_status" type="Status" minOccurs="1" />
				</xs:all>
			</xs:complexType>
			-->
			<xs:complexType name="ResponseCoupon">
				<xs:all>
					<xs:element name="code" type="xs:string" minOccurs="0" />
					<xs:element name="series_id" type="xs:integer" minOccurs="0" />
					<xs:element name="description" type="xs:string" minOccurs="0" />
					<xs:element name="discount_code" type="xs:string" minOccurs="0" />
					<xs:element name="valid_till" type="Date" minOccurs="0" />
					<xs:element name="discount_type" type="xs:string" minOccurs="0" />
					<xs:element name="discount_value" type="xs:string" minOccurs="0" />
					<xs:element name="discount_on" type="xs:string" minOccurs="0" />
					<xs:element name="detailed_info" type="xs:string" minOccurs="0" />
					<xs:element name="customer" type="ResponseCustomer" minOccurs="0" />
					<xs:element name="item_status" type="Status" minOccurs="1" />
				</xs:all>
			</xs:complexType>
			
			<!-- 
			<xs:complexType name="SeriesInfo">
				<xs:all>
					<xs:element name="description" type="xs:string" minOccurs="0" />
					<xs:element name="discount_code" type="xs:string" minOccurs="0" />
					<xs:element name="valid_till" type="xs:string" minOccurs="0" />
					<xs:element name="discount_type" type="xs:string" minOccurs="0" />
					<xs:element name="discount_value" type="xs:string" minOccurs="0" />
					<xs:element name="discount_on" type="xs:string" minOccurs="0" />
					<xs:element name="detailed_info" type="xs:string" minOccurs="0" />
				</xs:all>
			</xs:complexType>
			-->
			 
			<xs:complexType name="ResponseCustomer">
				<xs:all>
					<xs:element name="mobile" type="xs:string" minOccurs="0" />
					<xs:element name="email" type="xs:string" minOccurs="0" />
					<xs:element name="external_id" type="xs:string" minOccurs="0" />
					<xs:element name="user_id" type="xs:integer" minOccurs="0" />
				</xs:all>
			</xs:complexType>
			
			<xs:complexType name="Status">
				<xs:sequence>
					<xs:element name="success" type="xs:boolean" minOccurs="1" />
					<xs:element name="code" type="xs:integer" minOccurs="1" />
					<xs:element name="message" type="xs:string" minOccurs="1" />
				</xs:sequence>
			</xs:complexType>			
			
		</xs:schema>
	</wsdl:types>
	
	<wsdl:interface name="CouponIssueInterface">
		<wsdl:operation name="CouponIssue" 
			pattern="http://www.w3.org/ns/wsdl/in-out">
				<wsdl:input messageLabel="In" element="root"/>
				<wsdl:output messageLabel="Out" element="response"/>
		</wsdl:operation>
	</wsdl:interface>
	
	<wsdl:binding name="CouponIssueBinding" 
		interface="tns:CouponIssueInterface" 
		type="http://www.w3.org/ns/wsdl/http">
			<wsdl:operation ref="tns:CouponIssue"
				whttp:location="/v1.1/coupon/issue?format=xml" 
				whttp:method="POST" 
				whttp:inputSerialization="application/xml" 
				whttp:outputSerialization="application/xml" >
				<wsdl:input messageLabel="In" >
						<whttp:header name="Authorization" type="Authorization" required="true" />
					</wsdl:input>
			</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="CouponIssueService" 
		interface="tns:CouponIssueInterface">
			<wsdl:endpoint name="CouponIssueEndPoint" 
				binding="tns:CouponIssueBinding" 
				address="http://testing.capillary.in"/>
	</wsdl:service>
	
</wsdl:description>

